default:
  tags:
    - k8s

variables:
  GIT_SUBMODULE_STRATEGY: normal
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1
  BUILDKIT_INLINE_CACHE: 1
  DOCKER_TLS_CERTDIR: ""

stages:
  - prepare
  # - build
  - test
  - release
  - deploy
  # - publish

include:
- project: 'emundus/devops/ci-cd-templates'
  ref: main
  file: '.php_security_checker.yml'
- project: 'emundus/devops/ci-cd-templates'
  ref: main
  file: '.deployer.yml'
- project: 'emundus/devops/ci-cd-templates'
  ref: main
  file: '.release.yml'
- template: Security/Secret-Detection.gitlab-ci.yml

check-tchooz-version-job:
  stage: prepare
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
      when: always
    - when: never
  image: enix/ci-toolbox:1.23
  script:
    - .docker/scripts/file-search-in-gitlab-merge-request.sh "$CI_SERVER_URL" "$GITLAB_TOKEN" "$CI_PROJECT_ID" "$CI_MERGE_REQUEST_IID" "administrator/components/com_emundus/emundus.xml"

check-commit-prefixes-job:
  stage: prepare
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
      when: always
    - when: never
  image: enix/ci-toolbox:1.23
  script:
    - .docker/scripts/commit-prefix-compliance-check.sh "$CI_SERVER_URL" "$GITLAB_TOKEN" "$CI_PROJECT_ID" "$CI_MERGE_REQUEST_IID"

php_security_checker:
  variables:
      COMPOSER_PATH: "./libraries/emundus/composer.lock"

php_security_checker_gantry5:
  extends:
    - php_security_checker
  variables:
    COMPOSER_PATH: "./libraries/gantry5/composer.lock"

release-job:
  variables:
    IMAGE_TAG: "latest"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - administrator/components/com_emundus/emundus.xml
      when: on_success
    - when: never

deployer:
  stage: test
  environment: 
    name: testing
    deployment_tier: testing
  variables:
    DEPLOY_OPTIONS: "id=WcEF4kAHVHGMpbXhpM8Fx3rlkWQ4VOFP -o branch=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME -o COORD_USERNAME=$PLAYWRIGHT_RELEASE_COORD_USERNAME -o COORD_PASSWORD=$PLAYWRIGHT_RELEASE_COORD_PASSWORD -o SYSADMIN_USERNAME=$PLAYWRIGHT_RELEASE_SYSADMIN_USERNAME -o SYSADMIN_PASSWORD=$PLAYWRIGHT_RELEASE_SYSADMIN_PASSWORD -vv"
    DEPLOY_FILE: '-f tchooz-with-reset.php'
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual

deployer_test_playwright_in_schedule:
  stage: test
  environment: 
    name: testing
    deployment_tier: testing
  extends:
    - deployer
  variables:
    DEPLOY_OPTIONS: "id=WcEF4kAHVHGMpbXhpM8Fx3rlkWQ4VOFP -o branch=$CI_COMMIT_BRANCH -o COORD_USERNAME=$PLAYWRIGHT_RELEASE_COORD_USERNAME -o COORD_PASSWORD=$PLAYWRIGHT_RELEASE_COORD_PASSWORD -o SYSADMIN_USERNAME=$PLAYWRIGHT_RELEASE_SYSADMIN_USERNAME -o SYSADMIN_PASSWORD=$PLAYWRIGHT_RELEASE_SYSADMIN_PASSWORD -vv"
    DEPLOY_FILE: '-f tchooz-with-reset.php'
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

test_playwright:
  image: mcr.microsoft.com/playwright:v1.43.0-jammy
  script:
    - git clone $PLAYWRIGHT_ACCESS
    - cd playwright
    - npm ci
    - npx playwright install
    - npx playwright test
  variables:
    PLAYWRIGHT_ACCESS: $PLAYWRIGHT_ACCESS
    BASE_URL: $PLAYWRIGHT_RELEASE_BASE_URL
    COORD_USERNAME: $PLAYWRIGHT_RELEASE_COORD_USERNAME
    COORD_PASSWORD: $PLAYWRIGHT_RELEASE_COORD_PASSWORD
    SYSADMIN_USERNAME: $PLAYWRIGHT_RELEASE_SYSADMIN_USERNAME
    SYSADMIN_PASSWORD: $PLAYWRIGHT_RELEASE_SYSADMIN_PASSWORD
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "schedule"
  allow_failure: true
  artifacts:
    when: always
    expose_as: 'Playwright Report'
    paths:
      - playwright/playwright-report
    expire_in: 4 days
  needs:
    - job: deployer
      optional: true
    - job: deployer_test_playwright_in_schedule
      optional: true

deployer_release_candidate:
  stage: deploy
  environment: 
    name: release/auto
    deployment_tier: testing
  extends:
    - deployer
  variables:
    DEPLOY_OPTIONS: 'env=tchooz-v2 -vv'
    DEPLOY_FILE: '-f tchooz.php'
  rules:
    - if: $CI_COMMIT_BRANCH =~ "/^release\/.*/"