#docker-compose.yml for local development environment setup
services:
  joomla:
    container_name: joomla5
    build:
      context: ./.docker/
      dockerfile: Dockerfile
      args:
        # Set this variable to 1 to enable Xdebug (required for unit test coverage)
        test_env: 0
    image: tchooz-dev-app:2.0.0
    ports:
      - "8585:443"
      - "8383:443"
    restart: always
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_USER: user
      JOOMLA_DB_PASSWORD: password
      JOOMLA_DB_NAME: joomla5

      TCHOOZ_OFFLINE: 0
      TCHOOZ_OFFLINE_MESSAGE: 'This site is down for maintenance.<br />Please check back again soon.'
      TCHOOZ_DISPLAY_OFFLINE_MESSAGE: 1
      TCHOOZ_OFFLINE_IMAGE: images/logo.png
      TCHOOZ_SITENAME: Tchooz
      TCHOOZ_DEBUG: true
      TCHOOZ_DEBUG_LANG: 0
      TCHOOZ_LIVE_SITE: 'https://localhost:8585/'
      TCHOOZ_SECRET: TXGin8XS4BEqA8cA
      TCHOOZ_OFFSET: Europe/Paris
      TCHOOZ_MAILER: smtp
      TCHOOZ_MAIL_FROM: dev@emundus.fr
      TCHOOZ_MAIL_FROM_NAME: EMUNDUS Dev
      TCHOOZ_MAIL_SMTP_AUTH: 1
      TCHOOZ_MAIL_SMTP_USER: 
      TCHOOZ_MAIL_SMTP_PASS: 
      TCHOOZ_MAIL_SMTP_HOST: smtp.domain.com
      TCHOOZ_MAIL_SMTP_SECURITY: tls
      TCHOOZ_MAIL_SMTP_PORT: 2525
      TCHOOZ_CACHING: 0
      TCHOOZ_CACHE_HANDLER: file
      TCHOOZ_CACHE_LIFETIME: 15
      TCHOOZ_META_DESCRIPTION: Tchooz
      TCHOOZ_META_KEYS: tchooz
      TCHOOZ_LOG_PATH: /var/www/html/logs
      TCHOOZ_TMP_PATH: /var/www/html/tmp
      TCHOOZ_SESSION_LIFETIME: 15
      TCHOOZ_SESSION_HANDLER: database
      TCHOOZ_FORCE_SSL: 0
      TCHOOZ_REDIS_PERSIST: 0
      TCHOOZ_REDIS_HOST: joomlaredis
      TCHOOZ_REDIS_PORT: 6379
      TCHOOZ_REDIS_DB: 0
      TCHOOZ_MAIL_REPLY_TO:
      TCHOOZ_MAIL_REPLY_TO_NAME:
      TCHOOZ_SESSION_REDIS_PERSIST: 0
      TCHOOZ_SESSION_REDIS_HOST: joomlaredis
      TCHOOZ_SESSION_REDIS_PORT: 6379
      TCHOOZ_SESSION_REDIS_DB: 0
      TCHOOZ_BEHIND_LOADBALANCER: 0
      TCHOOZ_ADMIN_ACCESS_TOKEN: X3xAqXmxNkAKd5ckHBqmT
      TCHOOZ_COORD_USERNAME: coordinator
      TCHOOZ_COORD_MAIL: dev@emundus.fr
      TCHOOZ_COORD_FIRST_NAME: Dev
      TCHOOZ_COORD_LAST_NAME: EMUNDUS
      TCHOOZ_COORD_PASSWORD: password
      TCHOOZ_SYSADMIN_USERNAME: sysadmin
      TCHOOZ_SYSADMIN_MAIL: sysadmin@emundus.fr
      TCHOOZ_SYSADMIN_FIRST_NAME: Administrator
      TCHOOZ_SYSADMIN_LAST_NAME: EMUNDUS
      TCHOOZ_SYSADMIN_PASSWORD: password
      TCHOOZ_INSTANCE_ID: 999999
      TCHOOZ_CUSTOMER_ID: 999999
    volumes:
      - ./.docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - .:/var/www/html:z
    depends_on:
      joomladb:
        condition: service_healthy
    links:
      - joomladb:mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"

  joomladb:
    container_name: joomla5_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: joomla5
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      start_period: 15s
    ports:
      - "127.0.0.1:13308:3306"
    restart: always
    volumes:
      # (Required) Use a custom MySQL configuration for Tchooz
      - ./.docker/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      # (Config 1 - default: Tchooz fresh install with database persistant in a Docker volume
      - ./.docker/installation/databases:/docker-entrypoint-initdb.d
      # (Config 2: Tchooz fresh install with database persistant in a host volume
      # - ./.docker/data/mysql:/var/lib/mysql
      # - ./.docker/installation/databases:/docker-entrypoint-initdb.d
      # (Config 3: Tchooz custom install without database persistant
      # - /tmp/name_db_yyyy-mm-dd.sql:/docker-entrypoint-initdb.d/tchooz_custom_database.sql

  joomlaredis:
    container_name: joomla5_redis
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  blackfire:
    image: blackfire/blackfire:2
    ports: ["8307"]
    environment:
        # Define Blackfire Agent log vebosity level
        BLACKFIRE_LOG_LEVEL: 4

        # Exposes BLACKFIRE_SERVER_* environment variables from the host:
        BLACKFIRE_SERVER_ID: 
        BLACKFIRE_SERVER_TOKEN: 

        # Exposes BLACKFIRE_CLIENT_* environment variables
        # allowing the client to communicate with Blackfire's API:
        BLACKFIRE_CLIENT_ID: 
        BLACKFIRE_CLIENT_TOKEN: 
