FROM mysql:8.1 as builder
LABEL maintainer="eMundus <dev@emundus.fr>, EMUNDUS Development Team <support@emundus.fr>"

# That file does the DB initialization but also runs mysql daemon, by removing the last line it will only init
RUN ["sed", "-i", "s/exec \"$@\"/echo \"not running $@\"/", "/usr/local/bin/docker-entrypoint.sh"]

# needed for intialization
ENV MYSQL_RANDOM_ROOT_PASSWORD=yes
ENV MYSQL_DATABASE=joomla5
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password

# Copy Tchooz database (fresh install) to docker-initdb-entrypoint
COPY ["./.docker/installation/database-ci-env/core-build-ci-env.sql","/docker-entrypoint-initdb.d/core-build-ci-env.sql"] 

# Copy MySQL configuration
COPY ["./.docker/mysql/conf/my.cnf","/etc/mysql/conf.d/my.cnf"]
RUN chmod 664 /etc/mysql/conf.d/my.cnf

# Need to change the datadir to something else that /var/lib/mysql because the parent docker file defines it as a volume.
# https://docs.docker.com/engine/reference/builder/#volume :
#       Changing the volume from within the Dockerfile: If any build steps change the data within the volume after
#       it has been declared, those changes will be discarded.
RUN ["/usr/local/bin/docker-entrypoint.sh", "mysqld", "--datadir", "/initialized-db"]


FROM mysql:8.1
LABEL maintainer="Wilfried MAILLET <wilfried.maillet@emundus.fr>, EMUNDUS Development Team <support@emundus.fr>"

# Preloading of the database
COPY --from=builder /initialized-db /var/lib/mysql

# Copy MySQL custom configuration
COPY --from=builder /etc/mysql/conf.d/my.cnf /etc/mysql/conf.d/my.cnf

# Provide the Tchooz database initialization SQL script in a scenario where the container uses an empty volume 
COPY --from=builder /docker-entrypoint-initdb.d/core-build-ci-env.sql /docker-entrypoint-initdb.d/core-build-ci-env.sql