<?php
/**
 * @package     Tchooz\Enums\Import
 *
 * @copyright   Copyright (C) eMundus
 * @license     GNU General Public License version 2 or later
 */

namespace Tchooz\Enums\Import;

/**
 * Stable, language-neutral identifier for a row failure.
 */
enum ImportErrorCodeEnum: string
{
	case INVALID_INTEGER         = 'COM_EMUNDUS_IMPORT_VALIDATION_INVALID_INTEGER';
	case INVALID_NUMBER          = 'COM_EMUNDUS_IMPORT_VALIDATION_INVALID_NUMBER';
	case INVALID_BOOLEAN         = 'COM_EMUNDUS_IMPORT_VALIDATION_INVALID_BOOLEAN';
	case INVALID_DATE            = 'COM_EMUNDUS_IMPORT_VALIDATION_INVALID_DATE';
	case INVALID_EMAIL           = 'COM_EMUNDUS_IMPORT_VALIDATION_INVALID_EMAIL';
	case INVALID_URL             = 'COM_EMUNDUS_IMPORT_VALIDATION_INVALID_URL';
	case INVALID_ENUM_VALUE      = 'COM_EMUNDUS_IMPORT_VALIDATION_INVALID_ENUM_VALUE';
	case INVALID_ISO2            = 'COM_EMUNDUS_IMPORT_VALIDATION_INVALID_ISO2';
	case INVALID_ISO3            = 'COM_EMUNDUS_IMPORT_VALIDATION_INVALID_ISO3';
	case INVALID_ISO_4217        = 'COM_EMUNDUS_IMPORT_VALIDATION_INVALID_ISO_4217';
	case INVALID_PHONE_E164      = 'COM_EMUNDUS_IMPORT_VALIDATION_INVALID_PHONE_E164';
	case MISSING_REQUIRED_FIELDS = 'COM_EMUNDUS_IMPORT_MISSING_REQUIRED_FIELDS';
	case REFERENTIAL_VALUE_LABEL_COLLISION = 'COM_EMUNDUS_IMPORT_VALIDATION_REFERENTIAL_VALUE_LABEL_COLLISION';
	case AMBIGUOUS_REFERENTIAL_VALUE = 'COM_EMUNDUS_IMPORT_VALIDATION_AMBIGUOUS_REFERENTIAL_VALUE';
	case INVALID_REFERENTIAL_VALUE = 'COM_EMUNDUS_IMPORT_VALIDATION_INVALID_REFERENTIAL_VALUE';

	/**
	 * Non-translatable runtime failure (DB error, uncaught exception…). Its
	 * single param carries the raw message, surfaced verbatim by the '%s'
	 * translation string.
	 */
	case RUNTIME = 'COM_EMUNDUS_IMPORT_VALIDATION_RUNTIME';
}