/*! Fabrik */
/**
 * List Paginate
 *
 * @copyright: Copyright (C) 2005-2016  Media A-Team, Inc. - All rights reserved.
 * @license:   GNU/GPL http://www.gnu.org/copyleft/gpl.html
 */
define(["jquery","fab/fabrik"],function(t,i){"use strict";return new Class({initialize:function(i,s){this.form=i,this.options={liveSite:""},this.options=t.extend(this.options,s);var e=this.form.getForm(),o=this.form.id;this.pkfield=e.getElement("input[name=rowid]"),this.view=!0===this.form.options.editable?"form":"details",this.url=this.options.liveSite+"index.php?option=com_fabrik&format=raw&view=plugin&g=form&task=pluginAjax&plugin=paginate&method=xRecord&formid="+o+"&mode="+this.options.view+"&rowid=",this.watchButtons()},doUpdate:function(t){var s,e=JSON.parse(t),o="form"===this.view?e.data:e.html;this.options.ids=e.ids,this.form.formElements.each(function(t,i){if("_ro"!==i.substr(-3)){s=o[i];try{"null"!==typeOf(s)?t.updateUsingRaw()?t.update(e.data[i]):"form"===this.view?t.update(s):t.update(Encoder.htmlDecode(s)):t.update("")}catch(i){console.log(t,s,i)}}}.bind(this)),"form"===this.view&&(this.pkfield.value=o[this.options.pkey]),this.form.options.rowid=e.data[this.options.pkey],this.reScan(),window.fireEvent("fabrik.form.refresh",[e.post.rowid]),i.loader.stop(this.form.getBlock())},reScan:function(){"undefined"!=typeof Slimbox&&Slimbox.scanPage(),"undefined"!=typeof Lightbox&&Lightbox.init(),"undefined"!=typeof Mediabox&&Mediabox.scanPage(),this.form.getForm().getElements("*[data-paginate]").each(function(t){switch(t.get("data-paginate")){case"first":case"prev":0===this.options.ids.index?t.addClass("active"):t.removeClass("active");break;case"next":case"last":this.options.ids.index===this.options.ids.lastKey?t.addClass("active"):t.removeClass("active")}}.bind(this))},doNav:function(t){var s,e=!0;switch(t.get("data-paginate")){case"first":0===this.options.ids.index&&(e=!1),s=this.options.ids.first;break;case"last":this.options.ids.index===this.options.ids.lastKey&&(e=!1),s=this.options.ids.last;break;case"prev":0===this.options.ids.index&&(e=!1),s=this.options.ids.prev;break;case"next":this.options.ids.index===this.options.ids.lastKey&&(e=!1),s=this.options.ids.next}if(e){i.loader.start(this.form.getBlock());var o={};o[Joomla.getOptions("csrf.token")]=1;new Request({url:this.url+s,data:o,evalScripts:!0,onComplete:function(t){this.doUpdate(t)}.bind(this)}).send()}},watchButtons:function(){this.form.getForm().addEvent("click:relay(*[data-paginate])",function(t,i){t.preventDefault(),this.doNav(i)}.bind(this))}})});

