<?php
/**
 * @package     Joomla
 * @subpackage  com_emundus
 *
 * @copyright   Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

// No direct access to this file
use Joomla\CMS\Factory;
use Joomla\CMS\Language\LanguageHelper;
use Joomla\CMS\Language\Text;

defined('_JEXEC') or die('Restricted Access');

require_once(JPATH_BASE . DS . 'components' . DS . 'com_emundus' . DS . 'helpers' . DS . 'access.php');

// GLOBAL
Text::script('COM_EMUNDUS_ONBOARD_ADD_RETOUR');
Text::script('COM_EMUNDUS_ONBOARD_ADD_CONTINUER');
Text::script('COM_EMUNDUS_ONBOARD_OK');
Text::script('COM_EMUNDUS_ONBOARD_CANCEL');
Text::script('COM_EMUNDUS_ONBOARD_NEXT');
Text::script('COM_EMUNDUS_ONBOARD_LOAD_FILE');
Text::script('COM_EMUNDUS_ONBOARD_ADDCAMP_PROGRAM');
Text::script('COM_EMUNDUS_ONBOARD_SELECT_ALL');
Text::script('COM_EMUNDUS_ONBOARD_MODIFY');
Text::script('COM_EMUNDUS_ONBOARD_UPDATE_ICON');
Text::script('COM_EMUNDUS_SWAL_OK_BUTTON');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_CONTENT_PUBLISH');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_GENERAL_SAVE');
Text::script('COM_EMUNDUS_ACTIONS_CLEAR_BTN');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_GENERAL_UNSAVED');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_GENERAL_UNSAVED_MUST_TEST_MAIL');
Text::script('COM_EMUNDUS_ONBOARD_WARNING');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_GENERAL_SAVE_SUCCESS');
Text::script('COM_EMUNDUS_ONBOARD_SUCCESS');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_THEME_SAVE_SUCCESS');
Text::script('COM_EMUNDUS_ONBOARD_CANCEL_UPDATES');
Text::script('COM_EMUNDUS_ONBOARD_KEEP_NOTIFICATION');
Text::script('COM_EMUNDUS_ERROR');
Text::script('COM_EMUNDUS_MULTISELECT_NOKEYWORDS');
Text::script('COM_EMUNDUS_MULTISELECT_ADDKEYWORDS');
Text::script('COM_EMUNDUS_ONBOARD_THEME_ACCESSIBILITY');

// MENUS
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_MENU_STYLE');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_MENU_STYLE_DESC');
Text::script('COM_EMUNDUS_ONBOARD_CONTENT_TOOL_HOMEPAGE');
Text::script('COM_EMUNDUS_ONBOARD_CONTENT_TOOL_HOMEPAGE_DESC');
Text::script('COM_EMUNDUS_ONBOARD_CONTENT_TOOL_TERMS');
Text::script('COM_EMUNDUS_ONBOARD_CONTENT_TOOL_TERMS_DESC');
Text::script('COM_EMUNDUS_ONBOARD_CONTENT_TOOL_FOOTER');
Text::script('COM_EMUNDUS_ONBOARD_CONTENT_TOOL_FOOTER_DESC');
Text::script('COM_EMUNDUS_ONBOARD_CONTENT_TOOL_LEGAL_MENTION');
Text::script('COM_EMUNDUS_ONBOARD_CONTENT_TOOL_DATAS');
Text::script('COM_EMUNDUS_ONBOARD_CONTENT_TOOL_RIGHTS');
Text::script('COM_EMUNDUS_ONBOARD_CONTENT_TOOL_COOKIES');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_MENU_STATUS');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_MENU_STATUS_DESC');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_MENU_TAGS');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_MENU_TAGS_DESC');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_MENU_APPLICANTS');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_MENU_APPLICANTS_DESC');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_MENU_DATAS');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_MENU_DATAS_DESC');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_MENU_TRANSLATIONS');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_MENU_TRANSLATIONS_DESC');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_FILES_TOOL');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_FILES_TOOL_DESC');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_MENU_ATTACHMENT_STORAGE');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_MENU_ATTACHMENT_STORAGE_DESC');
Text::script('COM_EMUNDUS_ONBOARD_STATUSDESCRIPTION');
Text::script('COM_EMUNDUS_ONBOARD_STYLINGDESCRIPTION');
Text::script('COM_EMUNDUS_ONBOARD_TAGSDESCRIPTION');
Text::script('COM_EMUNDUS_ONBOARD_HOMEDESCRIPTION');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_ADDTAG');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATE_ENGLISH');
Text::script('COM_EMUNDUS_ONBOARD_COLORS');
Text::script('COM_EMUNDUS_ONBOARD_UPDATE_LOGO');
Text::script('COM_EMUNDUS_ONBOARD_DROP_HERE');
Text::script('COM_EMUNDUS_ONBOARD_REMOVE_FILE');
Text::script('COM_EMUNDUS_ONBOARD_CANCEL_UPLOAD');
Text::script('COM_EMUNDUS_ONBOARD_CANCEL_UPLOAD_CONFIRMATION');
Text::script('COM_EMUNDUS_ONBOARD_INVALID_FILE_TYPE');
Text::script('COM_EMUNDUS_ONBOARD_FILE_TOO_BIG');
Text::script('COM_EMUNDUS_ONBOARD_MAX_FILES_EXCEEDED');
Text::script('COM_EMUNDUS_ONBOARD_ERROR');
Text::script('COM_EMUNDUS_ONBOARD_PRIMARY_COLOR');
Text::script('COM_EMUNDUS_ONBOARD_SECONDARY_COLOR');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_UPDATE');
Text::script('COM_EMUNDUS_ONBOARD_COLOR_SUCCESS');
Text::script('COM_EMUNDUS_ONBOARD_CREATE_DATAS');
Text::script('COM_EMUNDUS_ONBOARD_IMPORT_DATAS');
Text::script('COM_EMUNDUS_ONBOARD_FIRSTNAME');
Text::script('COM_EMUNDUS_ONBOARD_FIRSTNAME_REQUIRED');
Text::script('COM_EMUNDUS_ONBOARD_LASTNAME');
Text::script('COM_EMUNDUS_ONBOARD_LASTNAME_REQUIRED');
Text::script('COM_EMUNDUS_ONBOARD_ADDCAMP_DESCRIPTION');
Text::script('COM_EMUNDUS_ONBOARD_VALUES');
Text::script('COM_EMUNDUS_ONBOARD_USERSDESCRIPTIONSETTINGS');
Text::script('COM_EMUNDUS_ONBOARD_LAST_CONNECTED');
Text::script('COM_EMUNDUS_ONBOARD_EMAIL');
Text::script('COM_EMUNDUS_ONBOARD_EMAIL_REQUIRED');
Text::script('COM_EMUNDUS_ONBOARD_DOSSIERS_STATUS');
Text::script('COM_EMUNDUS_ONBOARD_SEARCH');
Text::script('COM_EMUNDUS_ONBOARD_ACTIVATED');
Text::script('COM_EMUNDUS_ONBOARD_BLOCKED');
Text::script('COM_EMUNDUS_ONBOARD_NO_RESULTS_FOUND');
Text::script('COM_EMUNDUS_ONBOARD_ACTIONS');
Text::script('COM_EMUNDUS_ONBOARD_PROGRAM_ADDUSER');
Text::script('COM_EMUNDUS_ONBOARD_RESET_PASSWORD');
Text::script('COM_EMUNDUS_ONBOARD_RESET_PASSWORD_MESSAGE');
Text::script('COM_EMUNDUS_ONBOARD_LOCK_USER');
Text::script('COM_EMUNDUS_ONBOARD_UNLOCK_USER');
Text::script('COM_EMUNDUS_ONBOARD_ROLE');
Text::script('COM_EMUNDUS_ONBOARD_ROLE_REQUIRED');
Text::script('COM_EMUNDUS_ONBOARD_PROGRAM_ADMINISTRATOR');
Text::script('COM_EMUNDUS_ONBOARD_PROGRAM_EVALUATOR');
Text::script('COM_EMUNDUS_ONBOARD_UPDATE_DATAS');
Text::script('COM_EMUNDUS_ONBOARD_BLOCKED_USERS');
Text::script('COM_EMUNDUS_ONBOARD_COLUMNS');
Text::script('COM_EMUNDUS_ONBOARD_MY_COLUMNS');
Text::script('COM_EMUNDUS_ONBOARD_CSV_COLUMNS');
Text::script('COM_EMUNDUS_ONBOARD_CSV_ASSOCIATION');
Text::script('COM_EMUNDUS_ONBOARD_LEAST_ONE_COLUMN_REQUIRED');
Text::script('COM_EMUNDUS_ONBOARD_ADD_STATUS');
Text::script('COM_EMUNDUS_ONBOARD_SAVE');
Text::script('COM_EMUNDUS_ONBOARD_SAVED');
Text::script('COM_EMUNDUS_ONBOARD_COLUMN');
Text::script('COM_EMUNDUS_ONBOARD_PREVIEW');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATE_IN');
Text::script('COM_EMUNDUS_ONBOARD_ICON');
Text::script('COM_EMUNDUS_ONBOARD_UPDATE_BACKGROUND');
Text::script('COM_EMUNDUS_ONBOARD_BACKGROUND');
Text::script('COM_EMUNDUS_ONBOARD_DISPLAY_BACKGROUND');
Text::script('COM_EMUNDUS_ONBOARD_HOME_TITLE');
Text::script('COM_EMUNDUS_ONBOARD_HOME_CONTENT');
Text::script('COM_EMUNDUS_ONBOARD_ADDCAMP_PARAMETER');
Text::script('COM_EMUNDUS_ONBOARD_CANNOT_DELETE_STATUS');
Text::script('COM_EMUNDUS_ONBOARD_STYLE_TOOL_GENERAL');
Text::script('COM_EMUNDUS_FORM_BUILDER_ALLOWED_FORMATS');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_MENU_GENERAL');
Text::script('COM_EMUNDUS_ONBOARD_CUSTOM_PALETTE');
Text::script('COM_EMUNDUS_ONBOARD_ERROR_COLORS_SAME');
Text::script('COM_EMUNDUS_SETTINGS_CONTRAST_ERROR_PRIMARY');
Text::script('COM_EMUNDUS_SETTINGS_CONTRAST_ERROR_SECONDARY');
Text::script('COM_EMUNDUS_SETTINGS_ACCESSIBILITY_DETAILS');
Text::script('COM_EMUNDUS_SETTINGS_ACCESSIBILITY_DETAILS_NORMAL_TEXT');
Text::script('COM_EMUNDUS_SETTINGS_ACCESSIBILITY_DETAILS_LARGE_TEXT');
Text::script('COM_EMUNDUS_SETTINGS_ACCESSIBILITY_DETAILS_ICONS');
Text::script('COM_EMUNDUS_SETTINGS_ACCESSIBILITY_DETAILS_LOGIN_TEXT');
Text::script('COM_EMUNDUS_SETTINGS_FAILED_TO_UPDATE_STATUS');
Text::script('COM_EMUNDUS_SETTINGS_FAILED_TO_UPDATE_TAG');
Text::script('COM_EMUNDUS_SETTINGS_FORBIDDEN_EMPTY_STATUS');
Text::script('COM_EMUNDUS_SETTINGS_FORBIDDEN_EMPTY_TAG');
Text::script('COM_EMUNDUS_ONBOARD_RGAA_OK');

## TUTORIAL ##
Text::script('COM_EMUNDUS_ONBOARD_TUTORIAL_CAMPAIGN');
Text::script('COM_EMUNDUS_ONBOARD_TUTORIAL_FORM');
Text::script('COM_EMUNDUS_ONBOARD_TUTORIAL_FORMBUILDER');
Text::script('COM_EMUNDUS_ONBOARD_TUTORIAL_DOCUMENTS');
Text::script('COM_EMUNDUS_ONBOARD_TUTORIAL_PROGRAM');
Text::script('COM_EMUNDUS_ONBOARD_TUTORIAL_REWIND');
Text::script('COM_EMUNDUS_ONBOARD_TUTORIAL_REWIND_SUCCESS');
Text::script('COM_EMUNDUS_ONBOARD_REMOVE_ICON');
Text::script('COM_EMUNDUS_ONBOARD_REMOVE_ICON_TEXT');
Text::script('COM_EMUNDUS_ONBOARD_UPDATE_COLORS');
Text::script('COM_EMUNDUS_ONBOARD_DELETE_STATUS');
Text::script('COM_EMUNDUS_ONBOARD_INSERT_HEADER_IMAGE');
Text::script('COM_EMUNDUS_ONBOARD_INSERT_LOGO');
Text::script('COM_EMUNDUS_ONBOARD_INSERT_ICON');
Text::script('COM_EMUNDUS_ONBOARD_ICON_TIP_TEXT');
Text::script('COM_EMUNDUS_FORM_BUILDER_ICON_RECOMMENDED');
Text::script('COM_EMUNDUS_FORM_BUILDER_LOGO_RECOMMENDED');
Text::script('COM_EMUNDUS_ONBOARD_LOGO_TIP_TEXT');
Text::script('COM_EMUNDUS_FORM_BUILDER_COLORS_RECOMMENDED');
Text::script('COM_EMUNDUS_ONBOARD_BANNER_TIP_TEXT');
Text::script('COM_EMUNDUS_ONBOARD_UPDATE_BANNER');
## END ##

## eMUNDUS CONFIG ##
Text::script('COM_EMUNDUS_SWAL_HELP_TITLE');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_APPLICANT_CAN_RENEW');
Text::script('JNO');
Text::script('JYES');
Text::script('COM_EMUNDUS_APPLICANT_CAN_RENEW_CAMPAIGN');
Text::script('COM_EMUNDUS_APPLICANT_CAN_RENEW_YEAR');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_APPLICANT_CAN_EDIT_UNTIL_DEADLINE');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_APPLICANTS_DESC');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_APPLICANTS');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_APPLICANT_COPY_APPLICATION_FORM');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_APPLICANT_CAN_SUBMIT_ENCRYPTED');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_APPLICANT_CAN_SUBMIT_ANONYM_FILE');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_ALLOW_APPLICANT_TO_COMMENT');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_ALLOW_APPLICANT_TO_COMMENT_DESC');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_GENERAL_LIST_LIMIT');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_GENERAL_OTHER_USER_EDITING_SAME_FILE');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_GENERAL_OTHER_USER_EDITING_SAME_FILE_HELPTEXT');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_GENERAL_SITENAME');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_GENERAL_SITENAME_HELPTEXT');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_GENERAL_SITEDESCRIPTION');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_LIMIT_FILES_BY_STATUS');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_LIMIT_FILES_BY_STATUS_HELPTEXT');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_LIMIT_FILES_STATUSES');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_LIMIT_FILES_BY_STATUS_MAX');
## END ##

## TRANSLATIONS ##
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_GLOBAL');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_TRANSLATIONS');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_TRANSLATIONS_NO_LANGUAGES_AVAILABLE');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_ORPHELINS');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_ORPHELINS_TITLE');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_DEFAULT');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_DEFAULT_DESC');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_SECONDARY');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_SECONDARY_DESC');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_SELECT_LANGUAGE');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_NO_TRANSLATION_TITLE');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_NO_TRANSLATION_TEXT');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_SELECT_OBJECT');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_SELECT');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_TRANSLATIONS_AUTOSAVE');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_TRANSLATIONS_AUTOSAVE_PROGRESS');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_TRANSLATIONS_AUTOSAVE_LAST');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_NO_ORPHELINS_TITLE');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_NO_ORPHELINS_TEXT');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_ORPHELIN_CONFIRM_TRANSLATION');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_OTHER_LANGUAGE');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_SETUP_PROGRESSING');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_SETUP_SUCCESS');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_SUGGEST_LANGUAGE');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_SUGGEST_LANGUAGE_FIELD');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_SUGGEST_LANGUAGE_SEND');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_SUGGEST_LANGUAGE_SENDED');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_SUGGEST_LANGUAGE_SENDED_TEXT');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_MENU_CONTENT');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_MENU_CONTENT_DESC');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_ORPHANS_CONGRATULATIONS');
Text::script('COM_EMUNDUS_ONBOARD_BANNER');
Text::script('COM_EMUNDUS_FORM_BUILDER_RECOMMENDED_SIZE');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_EXPORT');
## END ##

## CONTENTELEMENT ##
Text::script('COM_EMUNDUS_CONTENTELEMENTS_SETUP_PROFILES');
Text::script('COM_EMUNDUS_CONTENTELEMENTS_SETUP_PROFILES_DESC');
Text::script('COM_EMUNDUS_CONTENTELEMENTS_SETUP_PROFILES_FABRIK_FORMS');
Text::script('COM_EMUNDUS_CONTENTELEMENTS_SETUP_CAMPAIGNS');
Text::script('COM_EMUNDUS_CONTENTELEMENTS_SETUP_CAMPAIGNS_DESC');

## END ##

## SU GED ##
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_CONFIGURATION');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_STORAGE');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_GED_ALFRESCO');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_GED_ALFRESCO_ADD_MENU');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_GED_ALFRESCO_DELETE');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_GED_ALFRESCO_CONF_WRITING');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_GED_ALFRESCO_SELECT_TYPE');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_GED_ALFRESCO_CAMPAIGN_TYPE');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_GED_ALFRESCO_FILE_TYPE');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_GED_ALFRESCO_USER_TYPE');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_GED_ALFRESCO_YEAR_TYPE');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_GED_ALFRESCO_OTHER');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_GED_ALFRESCO_NAME_WRITING');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_GED_ALFRESCO_SEPARATOR');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_GED_ALFRESCO_NAME_RESET');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_GED_ALFRESCO_NAME_TAGS_LIST');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_GED_ALFRESCO_NAME_SELECT_A_TAG');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_DOCTYPE');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_STATUS');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_STORAGE_TYPE');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_SYNCHRO');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_GED_ALFRESCO_SYNC_TYPE_LOCAL');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_GED_ALFRESCO_SYNC_TYPE_GED');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_SYNC_READ');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_SYNC_WRITE');
Text::script('COM_EMUNDUS_ONBOARD_ATTACHMENT_STORAGE_GO_BACK_TO_SELECT');
## END ##

Text::script('COM_EMUNDUS_ATTACHMENT_STORAGE_GED_ALFRESCO_ASPECTS');
Text::script('COM_EMUNDUS_ATTACHMENT_STORAGE_GED_ALFRESCO_ASPECTS_UPLOAD');
Text::script('COM_EMUNDUS_ATTACHMENT_STORAGE_GED_ALFRESCO_ASPECTS_MAPPING');
Text::script('COM_EMUNDUS_ATTACHMENT_STORAGE_GED_ALFRESCO_ASPECTS_UPLOAD_UPDATE');
Text::script('COM_EMUNDUS_ATTACHMENT_STORAGE_GED_ALFRESCO_ASPECTS_UPLOAD_ADD');
Text::script('COM_EMUNDUS_ATTACHMENT_STORAGE_GED_ALFRESCO_ASPECTS_UPLOAD_ADD_FROM_FILE');
Text::script('COM_EMUNDUS_ATTACHMENT_STORAGE_DEFAULT_ASPECTS_MAPPING');
Text::script('COM_EMUNDUS_ATTACHMENT_STORAGE_GED_ALFRESCO_ASPECTS_MISSING_ASPECT_FILE');

#-----------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------
## GLOBAL PARAMETERS ##
Text::script('COM_EMUNDUS_FORM_BUILDER_ELEMENT_PROPERTIES_GENERAL');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_MENUS_EMAIL');
Text::script('COM_EMUNDUS_FORM_BUILDER_ELEMENT_PROPERTIES_CONTENT');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_MENUS_MANAGE_FILES');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_MENUS_SUPPL_MOD');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_MENUS_INTEG');
#Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_TRANSLATIONS'); --- déjà fait plus haut

Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_PARAM_SITE');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_IMG_SITE');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_THEME_SITE');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_ANALATICS');

Text::script('COM_EMUNDUS_GLOBAL_PARAMS_AUTO_SAVE');

Text::script('COM_EMUNDUS_OPTIONAL');

Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_MANAG_SERVER_MAIL');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_EMAIL_HELPTEXT');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_MAIL_TOGGLE_MAILONLINE');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_MAIL_TOGGLE_DEFAULT_CONFIG');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_MAIL_TOGGLE_CUSTOM_CONFIG');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_MAIL_WARNING');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_PORT_WARNING');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_PORT_WARNING_HELPTEXT_TITLE');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_PORT_WARNING_HELPTEXT_BODY');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_MAIL_SUBSECTION_EMAIL_ADRESS');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_MAIL_SUBSECTION_SERVER_EMAIL_CONF');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_MAIL_SUBSECTION_SERVER_EMAIL_CONF_ADVICE');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_MAIL_TEST_MAIL_ERROR');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_MAIL_TEST_MAIL_SUCCESS');
Text::script('COM_EMUNDUS_ONBOARD_DOSSIERS_CLOSE');
Text::script('COM_EMUNDUS_CLICK_HERE_INFO');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_MAIL_TEST_BT');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_MAIL_CUSTOM_MODEL_BT');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_MAIL_CUSTOM_PLACEHOLDER_MAILFROM_NAME');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_MAIL_CUSTOM_PLACEHOLDER_MAILFROM_DOMAIN');

Text::script('COM_EMUNDUS_SURE_TO_DISABLE');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_MAIL_SURE_TO_DISABLE_TEXT');

Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_CAMPAIGN_PAGE');
#Text::script('COM_EMUNDUS_ONBOARD_CONTENT_TOOL_FOOTER'); --- déjà fait plus haut
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_RGPD');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_RGPD_HELPTEXT');
Text::script('COM_EMUNDUS_ONBOARD_CONTENT_TOOL_ACCESSIBILITY');

Text::script('COM_EMUNDUS_STATUS');
Text::script('COM_EMUNDUS_TAGS');
#Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_FILES_TOOL'); --- déjà fait plus haut

Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_SHARE_FILE');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_MAIL_GENERATION/PUBLISHING');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_EXPERT_INVITE');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_RULES_OF_PAY_PRODUCT');

Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_SAVE_CLOUD_FILE');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_ELECTRONIC_VERIF');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_API_INSEE');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_ADD_PIPE');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_PAYMENT');

Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_TRANSLATIONS');
#Text::script('COM_EMUNDUS_ONBOARD_TRANSLATION_TOOL_ORPHELINS'); --- déjà fait plus haut

Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SITE_FIELD_NAME'); // Nom du site
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SITE_LANG_PRIM'); // Langue principale
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SITE_OTHER_LANG'); // Autres Langues
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SITE_DESC'); // Description du site
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SITE_TIMEZONE'); // Fuseau horaire
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SITE_TIMEZONE_LAND'); // Pays
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SITE_TIMEZONE_CITY'); // Ville
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_BIRTHDAY_FORMAT'); // Format de date
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SITE_DATE_FORMAT_D/M/Y'); // Format de date
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SITE_DATE_FORMAT_M/D/Y'); // Format de date
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SITE_DATE_FORMAT_Y/M/D'); // Format de date
Text::script('COM_EMUNDUS_ATTACHMENTS_KEYWORDS'); // Mots clés
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SITE_NUMBER_LINES_LISTES'); // Nombre de lignes dans les listes

Text::script('COM_EMUNDUS_GLOBAL_PARAMS_THEME_SITE_ADV_PARA'); // Paramètres avancés
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_ANALATICS_HELPTEXT'); // helptext pour google analytics

Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_CAMP_SHOW'); // Afficher les campagnes
Text::script('COM_EMUNDUS_CAMPAIGN_ONGOING'); // Campagnes en cours
Text::script('COM_EMUNDUS_CAMPAIGN_YET_TO_COME'); // Campagnes à venir
Text::script('COM_EMUNDUS_CAMPAIGN_CLOSED'); // Campagnes cloturées

Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_CAMP_GROUP_BY'); // campagne Regrouper par
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_CAMP_GROUP_BY_MONTH'); // mois
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_CAMP_GROUP_BY_YEAR'); // année

Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_CAMP_ORGANIZE_BY'); // Organiser par
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_CAMP_ORGANIZE_BY_LAUCH_DATE'); // date de lancement
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_CAMP_ORGANIZE_BY_CLOSE_DATE'); // date de fin

#Text::script('COM_EMUNDUS_ONBOARD_CONTENT_TOOL_LEGAL_MENTION'); // Mentions légales --- déjà fait plus haut
#Text::script('COM_EMUNDUS_ONBOARD_CONTENT_TOOL_DATAS'); // Données personnelles --- déjà fait plus haut
#Text::script('COM_EMUNDUS_ONBOARD_CONTENT_TOOL_RIGHTS'); // Gestion de vos droits --- déjà fait plus haut
#Text::script('COM_EMUNDUS_ONBOARD_CONTENT_TOOL_COOKIES'); // Gestion des cookies --- déjà fait plus haut

Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_CONTENT_CANDIDATE_INTRO'); // Introduction pour le candidat
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_CONTENT_CANDIDATE_MULTIPLE_FILES'); // candidat a droit a Plusieurs dossiers
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_CONTENT_CANDIDATE_EDIT_UNTIL_DEADLINE'); // candidat peut modifier jusqu'à la date limite
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_CONTENT_CANDIDATE_SHOW_HISTORY'); // Afficher l'historique des candidatures

Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_CONTENT_ALERT_MOD_SIMUL'); // Alerte de modification simultanée
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_CONTENT_NUM_FILES_IN_LIST'); // Nombre de fichiers dans la liste
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_CONTENT_SHOW_DELETED_FILES'); // Afficher les fichiers supprimés
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_CONTENT_ALLOW_LOCK_PDF'); // Autoriser les PDF verrouillés
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTIONS_CONTENT_ALLOW_COPY_OF_FILES'); // Autoriser la copie des fichiers

Text::script('COM_EMUNDUS_SITESETTINGS_PARAM_INTRO'); // Intro des paramètres du site
Text::script('COM_EMUNDUS_SITESETTINGS_IMAGE_INTRO'); // Intro des images du site
Text::script('COM_EMUNDUS_SITESETTINGS_THEME_INTRO'); // Intro du thème du site
Text::script('COM_EMUNDUS_FILES_SETTINGS_INTRO'); // Intro de la gestion des dossiers

Text::script('PRESS_ENTER_TO_SELECT'); // Multiselect : supprimer
Text::script('PRESS_ENTER_TO_SELECT_GROUP'); // Multiselect : supprimer
Text::script('SELECTED'); // Multiselect : supprimer
Text::script('PRESS_ENTER_TO_REMOVE'); // Multiselect : supprimer
Text::script('PRESS_ENTER_TO_DESELECT_GROUP'); // Multiselect : supprimer

## EMAILS ##
Text::script('COM_EMUNDUS_FILTERS_CHECK_NONE');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_ENABLE');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_SENDER');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_REPLYTO');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_REPLY_TO_NAME');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_SENDER_NAME');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_SENDER_NAME_HELPTEXT');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_GLOBAL');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_CUSTOM');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_CONFIGURATION');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_CONFIGURATION_SMTP_HOST');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_CONFIGURATION_SMTP_PORT');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_CONFIGURATION_SMTP_SECURITY');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_CONFIGURATION_SMTP_ENABLE');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_CONFIGURATION_SMTP_USERNAME');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_CONFIGURATION_SMTP_PASSWORD');
Text::script('COM_EMUNDUS_ERROR_SMTP_HOST');
Text::script('COM_EMUNDUS_ERROR_SMTP_PORT');
Text::script('COM_EMUNDUS_ERROR_SMTP_AUTH');
Text::script('COM_EMUNDUS_ERROR_SMTP_TOGGLE_AUTH');
Text::script('COM_EMUNDUS_ERROR_MAIL_FUNCTION');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_NEED_TEST');
Text::script('COM_CONFIG_SENDMAIL_SUCCESS');
Text::script('COM_CONFIG_SENDMAIL_ERROR');
Text::script('COM_CONFIG_SENDMAIL_SUCCESS_FALLBACK');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_MAIL_SAVE_ANYWAY');
Text::script('COM_CONFIG_SENDMAIL_SUBJECT');
Text::script('COM_CONFIG_SENDMAIL_BODY');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_MAIL_TEST_MAIL_SUCCESS_BODY_LABEL_OTHER_EMAIL');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_MAIL_TEST_MAIL_SWAL_BUTTON');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_MAIL_CHECK_INPUT_MAIL');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_MAIL_CHECK_INPUT_MAIL_NO');
Text::script('COM_EMUNDUS_ONBOARD_SAVE_EMAIL_CONFIGURATION');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_MAIL_CHECK_INPUT_MAIL_NAME_EXP');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_MAIL_CHECK_INPUT_MAIL_DOMAIN_EXP');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_MAIL_CHECK_INPUT_MAIL_YES');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_GENERAL_TEST_MAIL_ERROR_EMAIL');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_MENUS_WEB_SECURITY');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_YOUR_LIVESITE');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_UPDATE_WEB_ADDRESS');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_UPDATE_WEB_ADDRESS_HELPTEXT');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_USE_OWN_SSL_CERTIFICATE');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_USE_OWN_SSL_CERTIFICATE_HELPTEXT');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_SSL_CERT');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_NEW_ADDRESS');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_NEW_ADDRESS_WARNING');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_NEW_ADDRESS_WARNING_2');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_OWN_SSL_ASK');
Text::script('COM_EMUNDUS_GLOBAL_EMAIL_ERRORS_DETAILS');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_PORT_WARNING_SEE_ALL');

Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_REPLYTO_ADRESS_HELPTEXT');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_REPLYTO_HELPTEXT');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_SENDER_ADRESS_HELPTEXT');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_HOSTSMTP_HELPTEXT');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_HOSTPASSWORD_HELPTEXT');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_PORT_HELPTEXT');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_SECURITY_HELPTEXT');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_TECHNICAL_CONTACTS');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_TECHNICAL_CONTACTS_HELPTEXT');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_CONFIRMATION');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_CONFIRMATION_BUTTON');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_CONFIRMATION_TEXT');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_RESUME');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_NEW_ADDRESS_TO_UPDATE');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_OWN_SSL_CERTIFICATE');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_REQUEST_SENT');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_CURRENT_REQUESTS_PENDING');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_REQUEST_PENDING');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_REQUEST');
Text::script('COM_EMUNDUS_GLOBAL_EMAIL');

Text::script('COM_EMUNDUS_STATUS_INTRO');
Text::script('COM_EMUNDUS_TAGS_INTRO');

Text::script('COM_EMUNDUS_ONBOARD_ERROR_MESSAGE');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_ADD');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_DISABLE');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_ENABLE');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_UPDATE');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_UPDATE_BUTTON');

Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_TEAMS_SETUP');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_TEAMS_SETUP_DESC');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_TEAMS_SETUP_REQUIREMENTS');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_TEAMS_SETUP_CLIENT_ID');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_TEAMS_SETUP_CLIENT_SECRET');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_TEAMS_SETUP_TENANT_ID');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_TEAMS_SETUP_SUCCESS');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_TEAMS_SETUP_SUCCESS_DESC');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_TEAMS_SETUP_EMAIL');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_DYNAMICS_SETUP_DOMAIN');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_DYNAMICS_SETUP');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_DYNAMICS_SETUP_DESC');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_DYNAMICS_SETUP_SUCCESS');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_DYNAMICS_SETUP_SUCCESS_DESC');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_DYNAMICS_SETUP_AUTH');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_DYNAMICS_SETUP_CONFIG');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_AMMON_SETUP_REQUIREMENTS');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_AMMON_SETUP');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_AMMON_SETUP_DESC');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_AMMON_SETUP_SUCCESS');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_AMMON_SETUP_SUCCESS_DESC');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_AMMON_SETUP_FAILED');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_AMMON_SETUP_LOGIN');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_AMMON_SETUP_PASSWORD');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_AMMON_SETUP_API_KEY');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_AMMON_SETUP_BASE_URL');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_OVH_SETUP_REQUIREMENTS');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_OVH_SETUP');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_OVH_SETUP_DESC');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_OVH_SETUP_CLIENT_ID');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_OVH_SETUP_CLIENT_SECRET');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_OVH_SETUP_CONSUMER_KEY');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_OVH_SETUP_SUCCESS');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_OVH_SETUP_SUCCESS_DESC');
## END ##

Text::script('COM_EMUNDUS_ATTACHMENT_STORAGE_GED_ALFRESCO_ASPECTS');
Text::script('COM_EMUNDUS_ATTACHMENT_STORAGE_GED_ALFRESCO_ASPECTS_UPLOAD');
Text::script('COM_EMUNDUS_ATTACHMENT_STORAGE_GED_ALFRESCO_ASPECTS_MAPPING');
Text::script('COM_EMUNDUS_ATTACHMENT_STORAGE_GED_ALFRESCO_ASPECTS_UPLOAD_UPDATE');
Text::script('COM_EMUNDUS_ATTACHMENT_STORAGE_GED_ALFRESCO_ASPECTS_UPLOAD_ADD');
Text::script('COM_EMUNDUS_ATTACHMENT_STORAGE_GED_ALFRESCO_ASPECTS_UPLOAD_ADD_FROM_FILE');
Text::script('COM_EMUNDUS_ATTACHMENT_STORAGE_DEFAULT_ASPECTS_MAPPING');
Text::script('COM_EMUNDUS_ATTACHMENT_STORAGE_GED_ALFRESCO_ASPECTS_MISSING_ASPECT_FILE');

Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_REPLYTO_ADRESS_HELPTEXT');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_REPLYTO_HELPTEXT');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_SENDER_ADRESS_HELPTEXT');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_HOSTSMTP_HELPTEXT');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_HOSTPASSWORD_HELPTEXT');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_PORT_HELPTEXT');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_EMAIL_SECURITY_HELPTEXT');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_TECHNICAL_CONTACTS');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_TECHNICAL_CONTACTS_HELPTEXT');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_CONFIRMATION');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_CONFIRMATION_BUTTON');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_CONFIRMATION_TEXT');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_RESUME');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_NEW_ADDRESS_TO_UPDATE');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_OWN_SSL_CERTIFICATE');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_REQUEST_SENT');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_CURRENT_REQUESTS_PENDING');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_REQUEST_PENDING');
Text::script('COM_EMUNDUS_GLOBAL_WEB_SECURITY_REQUEST');
Text::script('COM_EMUNDUS_GLOBAL_EMAIL');

Text::script('COM_EMUNDUS_STATUS_INTRO');
Text::script('COM_EMUNDUS_TAGS_INTRO');
## END ##

## WORKFLOW ##
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_MENUS_WORKFLOWS');
Text::script('COM_EMUNDUS_ONBOARD_WORKFLOWS');
Text::script('COM_EMUNDUS_ONBOARD_ADD_WORKFLOW');
Text::script('COM_EMUNDUS_ONBOARD_RESULTS');
Text::script('COM_EMUNDUS_ONBOARD_LABEL');
Text::script('COM_EMUNDUS_WORKFLOW_DELETE_WORKFLOW_CONFIRMATION');
Text::script('COM_EMUNDUS_WORKFLOW_STEP_TYPES');
Text::script('COM_EMUNDUS_WORKFLOW_ADD_CHILDREN_STEP_TYPE');
Text::script('COM_EMUNDUS_WORKFLOW_STEP_TYPE_APPLICANT');
Text::script('COM_EMUNDUS_WORKFLOW_STEP_TYPE_EVALUATOR');
Text::script('SAVE');
Text::script('COM_EMUNDUS_WORKFLOW_SAVE_STEP_TYPES_SUCCESS');
## END ##

## ADDONS ##
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_UPDATE');
Text::script('COM_EMUNDUS_ADDONS_MESSENGER');
Text::script('COM_EMUNDUS_ADDONS_MESSENGER_DESC');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_MESSENGER_SETUP');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_MESSENGER_ANONYMOUS_COORDINATOR');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_MESSENGER_SEND_SUMMARY_EMAILS');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_MESSENGER_NOTIFY_USERS_ASSOCIATED');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_MESSENGER_USERS_WITH_GROUPS');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_MESSENGER_USERS_WITH_GROUPS_HELPTEXT');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_MESSENGER_USERS');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_MESSENGER_FREQUENCY');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_MESSENGER_FREQUENCY_DAILY');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_MESSENGER_FREQUENCY_WEEKLY');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_MESSENGER_FREQUENCY_CUSTOM');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_MESSENGER_FREQUENCY_CUSTOM_FIELD');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_MESSENGER_FREQUENCY_CUSTOM_FIELD_HELPTEXT');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_MESSENGER_FREQUENCY_CUSTOM_FIELD_HOURS');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_MESSENGER_FREQUENCY_CUSTOM_FIELD_DAYS');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_MESSENGER_FREQUENCY_CUSTOM_FIELD_WEEKS');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_MESSENGER_MESSAGE_IN_NOTIFICATION');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_MESSENGER_SETUP_FREQUENCY_ERROR');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_MESSENGER_SETUP_FREQUENCY_ERROR_DAILY_DESC');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_MESSENGER_SETUP_FREQUENCY_ERROR_WEEKLY_DESC');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_MESSENGER_SETUP_SUCCESS');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_MESSENGER_SETUP_SUCCESS_DESC');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_MESSENGER_NOTIFICATIONS_EMAIL_SHORTCUT');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_SMS_SHORTCUT');
Text::script('COM_EMUNDUS_SMS_ADDON_CONFIGURATION');
Text::script('COM_EMUNDUS_SMS_ENCODING');
Text::script('COM_EMUNDUS_ADDONS_SMS');
Text::script('COM_EMUNDUS_ADDONS_SMS_DESC');
Text::script('COM_EMUNDUS_SMS_SERVICE');
Text::script('COM_EMUNDUS_SMS_SERVICE_INFO');
Text::script('COM_EMUNDUS_SMS_ADDON_CONFIGURATION_SAVED');
Text::script('COM_EMUNDUS_SUCCESS');
Text::script('COM_EMUNDUS_SMS_SELECT_ENCODING');
Text::script('COM_EMUNDUS_ADDONS_IMPORT');
Text::script('COM_EMUNDUS_ADDONS_IMPORT_DESC');
Text::script('COM_EMUNDUS_ADDONS_CHOICES');
Text::script('COM_EMUNDUS_ADDONS_CHOICES_DESC');
Text::script('COM_EMUNDUS_ADDONS_AUTOMATION');
Text::script('COM_EMUNDUS_ADDONS_AUTOMATION_DESC');

Text::script('COM_EMUNDUS_SOGECOMMERCE_SETUP_TITLE');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_SOGECOMMERCE_SETUP_AUTH');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_SOGECOMMERCE_SETUP_PARAMS');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_SOGECOMMERCE_SETUP_CLIENT_ID');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_SOGECOMMERCE_SETUP_CLIENT_SECRET');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_SOGECOMMERCE_SETUP_ENDPOINT_URL');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_SOGECOMMERCE_SETUP_SUCCESS_URL');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_SOGECOMMERCE_SETUP_SAVE');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_SOGECOMMERCE_SETUP_MODE');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_SOGECOMMERCE_SETUP_MODE_TEST');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_SOGECOMMERCE_SETUP_MODE_PROD');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_SOGECOMMERCE_SETUP_HISTORY');
Text::script('COM_EMUNDUS_ONBOARD_SOGECOMMERCE_HISTORY');
Text::script('COM_EMUNDUS_ONBOARD_SOGECOMMERCE_HISTORY_INTRO');
Text::script('COM_EMUNDUS_ONBOARD_SOGECOMMERCE_NO_HISTORY');
Text::script('COM_EMUNDUS_ONBOARD_SOGECOMMERCE_HISTORY_DETAIL');
Text::script('COM_EMUNDUS_SOGECOMMERCE_HISTORY_TRANSACTION_ID');
Text::script('COM_EMUNDUS_SOGECOMMERCE_HISTORY_TRANSACTION_CREATED_AT');
Text::script('COM_EMUNDUS_SOGECOMMERCE_HISTORY_STATUS');
Text::script('COM_EMUNDUS_ONBOARD_VISUALIZE');
Text::script('COM_EMUNDUS_LIST_CLOSE_PREVIEW');
Text::script('COM_EMUNDUS_STRIPE_SETUP_TITLE');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_STRIPE_SETUP_CLIENT_SECRET');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_STRIPE_SETUP_WEBHOOK_SECRET');

Text::script('COM_EMUNDUS_PAYMENT_ADDON_CONFIGURATION');
Text::script('COM_EMUNDUS_SETTINGS_ADDONS_PAYMENT_CURRENCY');
Text::script('COM_EMUNDUS_PAYMENT_ADDON_CONFIGURATION_SAVED');
## END ##

Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_PRODUCTION_MODE');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_CREATE_WEBHOOK');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_BEARER_TOKEN');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_SETUP');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_SETUP_DESC');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_SETUP_SUCCESS');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_SETUP_SUCCESS_DESC');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_QUOTA');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_SIGN_COUNT');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_CREATE_WEBHOOK_HELP_TITLE');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_CREATE_WEBHOOK_HELP');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_EXPIRATION_DATE');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_EXPIRATION_DATE_HELP');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_SIGNATURE_LEVEL');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_SIGNATURE_LEVEL_HELP_TITLE');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_SIGNATURE_LEVEL_HELP');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_SIGNATURE_LEVEL_ELECTRONIC');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_SIGNATURE_LEVEL_ADVANCED');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_SIGNATURE_LEVEL_QUALIFIED');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_SIGNATURE_AUTHENTICATION_MODE');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_SIGNATURE_AUTHENTICATION_MODE_HELP_TITLE');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_SIGNATURE_AUTHENTICATION_MODE_HELP');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_SIGNATURE_AUTHENTICATION_MODE_EMAIL');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_YOUSIGN_SIGNATURE_AUTHENTICATION_MODE_SMS');

Text::script('COM_EMUNDUS_GLOBAL_PARAMS_MENUS_USERS');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_MULTIFACTOR_AUTHENTICATION');
Text::script('COM_EMUNDUS_SETTINGS_2FA_AVAILABLE_METHODS');
Text::script('COM_EMUNDUS_SETTINGS_2FA_AVAILABLE_METHODS_HELPTEXT');
Text::script('COM_EMUNDUS_SETTINGS_2FA_FORCE_FOR_PROFILES');
Text::script('COM_EMUNDUS_SETTINGS_2FA_USERS_WITH_PROFILES');
Text::script('COM_EMUNDUS_SETTINGS_2FA_USERS_WITH_PROFILES_HELPTEXT');
Text::script('COM_EMUNDUS_SETTINGS_2FA_AVAILABLE_METHODS_TOTP');
Text::script('COM_EMUNDUS_SETTINGS_2FA_AVAILABLE_METHODS_EMAIL');
Text::script('COM_EMUNDUS_SETTINGS_2FA_APPLICANT');
Text::script('COM_EMUNDUS_SETTINGS_2FA_SETUP_SUCCESS');
Text::script('COM_EMUNDUS_SETTINGS_2FA_FOR_SSO');

Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_SECURITY_RULES');
Text::script('COM_EMUNDUS_SETTINGS_DISABLE_INACTIVE_ACCOUNTS_AFTER_DELAY');
Text::script('COM_EMUNDUS_SETTINGS_DELETE_TESTING_ACCOUNTS_AFTER_DELAY');

Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_USER_CATEGORIES');
Text::script('COM_EMUNDUS_ONBOARD_SETTINGS_USER_CATEGORIES_INTRO');
Text::script('COM_EMUNDUS_ONBOARD_ENABLED_USER_CATEGORY');
Text::script('COM_EMUNDUS_ONBOARD_ADD_USER_CATEGORY');
Text::script('COM_EMUNDUS_ONBOARD_DELETE_USER_CATEGORY');
Text::script('COM_EMUNDUS_ONBOARD_SHOW_ARCHIVED_USER_CATEGORY');
Text::script('COM_EMUNDUS_ONBOARD_MANDATORY_USER_CATEGORY');

Text::script('COM_EMUNDUS_CHOICES_ADDON_CONFIGURATION');
Text::script('COM_EMUNDUS_CHOICES_ADDON_CONFIGURATION');
Text::script('COM_EMUNDUS_CHOICES_ADDON_CONFIGURATION_HELP');
Text::script('COM_EMUNDUS_CHOICES_ADDON_ASK_MODALITE_LABEL');
Text::script('COM_EMUNDUS_CHOICES_ADDON_ASK_MODALITE_HELPTEXT');
Text::script('COM_EMUNDUS_CHOICES_ADDON_MODALITE_NAME_LABEL');
Text::script('COM_EMUNDUS_ONBOARD_PARAMS_ADD_REPEATABLE_MODALITE');
Text::script('COM_EMUNDUS_CHOICES_ADDON_CONFIGURATION_MODALITE_OPTIONS');
Text::script('COM_EMUNDUS_CHOICES_ADDON_CONFIGURATION_LOCATION_OPTIONS');
Text::script('COM_EMUNDUS_ONBOARD_PARAMS_ADD_REPEATABLE_LOCATION');
Text::script('COM_EMUNDUS_CHOICES_ADDON_LOCATION_NAME_LABEL');
Text::script('COM_EMUNDUS_CHOICES_ADDON_ASK_LOCATION_LABEL');
Text::script('COM_EMUNDUS_CHOICES_ADDON_ASK_LOCATION_HELPTEXT');
Text::script('COM_EMUNDUS_CHOICES_ADDON_ASK_BOURSE_LABEL');
Text::script('COM_EMUNDUS_CHOICES_ADDON_ASK_BOURSE_HELPTEXT');

Text::script('COM_EMUNDUS_GLOBAL_PARAMS_MENUS_ANALYTICS');
Text::script('COM_EMUNDUS_SETTINGS_ANALYTCS_ENABLED');
Text::script('COM_EMUNDUS_SETTINGS_ANALYTICS_COUNT_PAGES_VISITED');
Text::script('COM_EMUNDUS_SETTINGS_ANALYTICS_PERIOD_ALL_TIME');
Text::script('COM_EMUNDUS_SETTINGS_ANALYTICS_PERIOD_YEAR');
Text::script('COM_EMUNDUS_SETTINGS_ANALYTICS_PERIOD_LAST_30_DAYS');
Text::script('COM_EMUNDUS_SETTINGS_ANALYTICS_PERIOD_LAST_7_DAYS');
Text::script('COM_EMUNDUS_SETTINGS_ANALYTICS_PERIOD_TODAY');
Text::script('COM_EMUNDUS_SETTINGS_ANALYTICS_INFO');


$lang         = Factory::getApplication()->getLanguage();
$short_lang   = substr($lang->getTag(), 0, 2);
$current_lang = $lang->getTag();
$languages    = LanguageHelper::getLanguages();
if (count($languages) > 1) {
	$many_languages = '1';
	require_once JPATH_SITE . '/components/com_emundus/models/translations.php';
	$m_translations = new EmundusModelTranslations();
	$default_lang   = $m_translations->getDefaultLanguage()->lang_code;
}
else {
	$many_languages = '0';
	$default_lang   = $current_lang;
}

$user               = Factory::getApplication()->getIdentity();
$coordinator_access = EmundusHelperAccess::asCoordinatorAccessLevel($user->id);
$sysadmin_access    = EmundusHelperAccess::isAdministrator($user->id);

require_once(JPATH_ROOT . '/components/com_emundus/helpers/cache.php');
$hash = EmundusHelperCache::getCurrentGitHash();
?>

<style link="media/com_emundus_vue/app_emundus.css?<?php echo $hash ?>"></style>

<div id="em-component-vue"
     component="Settings"
     shortLang="<?= $short_lang ?>"
     currentLanguage="<?= $current_lang ?>"
     defaultLang="<?= $default_lang ?>"
     coordinatorAccess="<?= $coordinator_access ?>"
     sysadminAccess="<?= $sysadmin_access ?>"
     manyLanguages="<?= $many_languages ?>"
></div>

<script src="media/com_emundus/js/settings.js?<?php echo $hash ?>"></script>
<script type="module" src="media/com_emundus_vue/app_emundus.js?<?php echo $hash ?>"></script>
