css:
  -
    location: 'https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined'
    inline: ''
    extra: '{  }'
    priority: '0'
    name: 'Material Icons'
  -
    location: 'gantry-assets://custom/scss/quill.scss'
    inline: ''
    extra: '{  }'
    priority: '0'
    name: Quill
  -
    location: 'gantry-assets://custom/scss/main.compiled.css'
    inline: ''
    extra: '{  }'
    priority: '0'
    name: Main
  -
    location: 'gantry-assets://custom/scss/global.scss'
    inline: ''
    extra: {  }
    priority: '0'
    name: Global
  -
    location: 'gantry-assets://custom/scss/custom.scss'
    inline: ''
    extra: '{  }'
    priority: '0'
    name: Custom
  -
    location: modules/mod_falang/style/mod_falang_emundus.css
    inline: ''
    extra: '{  }'
    priority: '0'
    name: Falang
  -
    location: modules/mod_emundus_footer/css/mod_emundus_footer.css
    inline: ''
    extra: '{  }'
    priority: '0'
    name: Footer
  -
    location: modules/mod_emundusmenu/style/mod_emundusmenu.css
    inline: ''
    extra: '{  }'
    priority: '0'
    name: Menu