name: _error
timestamp: 1724763136
version: 7
preset:
  image: 'gantry-admin://images/layouts/3-col.png'
  name: _joomla_-_gantry4
  timestamp: 1530009501
positions:
  breadcrumb: Breadcrumb
  drawer: Drawer
  drawer-a: 'Drawer A'
  drawer-b: 'Drawer B'
  drawer-c: 'Drawer C'
sections:
  drawer: Drawer
  top: Top
  navigation: Navigation
  showcase: Showcase
  feature: Feature
  utility: Utility
  breadcrumb: Breadcrumb
  maintop: Maintop
  mainbottom: Mainbottom
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  main-mainbody: Mainbody
  footer: Footer
  offcanvas: Offcanvas
particles:
  position:
    position-position-2966: Breadcrumb
    position-position-3690: Drawer
    position-position-7693: 'Drawer A'
    position-position-5955: 'Drawer B'
    position-position-1889: 'Drawer C'
  messages:
    system-messages-2171: 'System Messages'
  content:
    system-content-9679: 'Page Content'
  module:
    position-module-7703: 'Mobile Menu'
    position-module-7526: 'User menu phone'
inherit:
  default:
    drawer: drawer
    showcase: showcase
    position-position-2966: position-position-6366
    feature: feature
    system-messages-2171: system-messages-7972
    utility: utility
    position-position-3690: position-position-6313
    position-position-7693: position-position-3312
    position-position-5955: position-position-3137
    position-position-1889: position-position-3100
    breadcrumb: breadcrumb
    maintop: maintop
    mainbottom: mainbottom
    extension: extension
    copyright: copyright
    offcanvas: offcanvas
    position-module-7703: position-module-2455
    position-module-7526: position-module-3093
