version: 2
preset:
  image: 'gantry-admin://images/layouts/3-col.png'
  name: _joomla_-_gantry4
  timestamp: 1530009501
layout:
  drawer: {  }
  top: {  }
  navigation: {  }
  showcase: {  }
  feature: {  }
  utility: {  }
  breadcrumb: {  }
  maintop: {  }
  /container-main/:
    -
      -
        main-mainbody:
          -
            - system-content-9679
  mainbottom: {  }
  extension: {  }
  bottom: {  }
  footer: {  }
  copyright: {  }
  offcanvas: {  }
structure:
  drawer:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  top:
    type: section
  navigation:
    type: section
  showcase:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  feature:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  utility:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  breadcrumb:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  maintop:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  main-mainbody:
    title: Mainbody
    attributes:
      class: ''
  container-main:
    attributes:
      boxed: ''
      class: ''
      extra: {  }
  mainbottom:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  extension:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  bottom:
    type: section
  copyright:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
