<?php
use Joomla\CMS\Factory;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Layout\LayoutHelper;
use Tchooz\Factories\LayoutFactory;
use Tchooz\Repositories\Actions\ActionRepository;

$translations = [
    'COM_EMUNDUS_POLLS',
    'COM_EMUNDUS_ONBOARD_LABEL_POLL',
    'COM_EMUNDUS_NO_POLLS_FOUND',
    'COM_EMUNDUS_POLLS_ADD',
    'COM_EMUNDUS_ONBOARD_ACTION_DUPLICATE',
    'COM_EMUNDUS_ONBOARD_MODIFY',
    'COM_EMUNDUS_ONBOARD_ACTION_DELETE',
    'COM_EMUNDUS_ONBOARD_ACTION_SHOW_DETAILS',
    'COM_EMUNDUS_POLLS_RUN',
    'COM_EMUNDUS_POLLS_RUN_CONFIRM',
    'COM_EMUNDUS_POLLS_ACTION_REPLY',
    'COM_EMUNDUS_POLLS_SLOT_DATES',
    'COM_EMUNDUS_POLL_REPLY_STATE',
    'COM_EMUNDUS_POLL_FIELD_LOCATION_LABEL',
    'COM_EMUNDUS_POLL_REPLY_ANSWER',
    'COM_EMUNDUS_POLL_REPLY_POLL',
    'COM_EMUNDUS_POLL_REPLY_COMMENT',
    'COM_EMUNDUS_POLL_REPLY_COMMENT_PLACEHOLDER',
    'COM_EMUNDUS_POLL_REPLY_VALIDATE',
    'COM_EMUNDUS_POLL_REPLY_STATE_NO_ANSWER',
    'COM_EMUNDUS_POLL_REPLY_AVAILABLE',
    'COM_EMUNDUS_POLL_REPLY_IF_NEEDED',
    'COM_EMUNDUS_POLL_REPLY_UNAVAILABLE',
    'COM_EMUNDUS_POLL_REPLY_SELECTED_SLOTS',
    'COM_EMUNDUS_POLL_REPLY_SAVE',
    'COM_EMUNDUS_POLL_REPLY_BULK_STATE_LABEL',
    'COM_EMUNDUS_POLL_REPLY_BULK_STATE_PLACEHOLDER',
    'COM_EMUNDUS_POLL_REPLY_BULK_COMMENT_LABEL',
    'COM_EMUNDUS_POLL_REPLY_BULK_COMMENT_PLACEHOLDER',
    'COM_EMUNDUS_POLL_REPLY_SELECTION',
    'COM_EMUNDUS_POLL_REPLY_SELECT_ALL',
    'COM_EMUNDUS_POLL_REPLY_DESELECT_ALL',
    'COM_EMUNDUS_POLL_REPLY_LOCKED',
    'COM_EMUNDUS_POLL_REPLY_LOCKED_INFO',
    'COM_EMUNDUS_POLL_SLOT_CAPACITY_NEEDED',
    'COM_EMUNDUS_POLL_RESULTS',
    'COM_EMUNDUS_POLL_FIELD_NEEDED_PARTICIPANTS',
    'COM_EMUNDUS_POLL_SLOT_DETAILS_TITLE',
    'COM_EMUNDUS_POLL_SLOT_DETAILS_PARTICIPANTS',
    'COM_EMUNDUS_POLL_SLOT_DETAILS_RESEND',
    'COM_EMUNDUS_POLL_SLOT_DETAILS_COMMENT',
    'COM_EMUNDUS_POLL_FIELD_STATUS_LABEL',
    'COM_EMUNDUS_ONBOARD_FILTER_ALL',
    'COM_EMUNDUS_CAMPAIGN_STATUS_UPCCOMING',
    'COM_EMUNDUS_CAMPAIGN_STATUS_OPEN',
    'COM_EMUNDUS_CAMPAIGN_STATUS_CLOSED',
    'COM_EMUNDUS_POLLS_FILTER_TO_REPLY',
    'COM_EMUNDUS_POLLS_FILTER_TO_REPLY_YES',
    'COM_EMUNDUS_POLL_NOTIFICATION_BODY',
    'COM_EMUNDUS_POLL_NOTIFICATION_SUBJECT',
    'COM_EMUNDUS_POLL_CONTACT_PARTICIPANTS_TITLE',
    'COM_EMUNDUS_POLL_CONTACT_TO',
    'COM_EMUNDUS_POLL_CONTACT_SUBJECT',
    'COM_EMUNDUS_POLL_CONTACT_REPLY_TO',
    'COM_EMUNDUS_POLL_CONTACT_REPLY_TO_PLACEHOLDER',
    'COM_EMUNDUS_POLL_CONTACT_SEND',
    'COM_EMUNDUS_POLL_SLOT_DETAILS_RESEND_ALL',
    'COM_EMUNDUS_POLL_RUN_TITLE',
    'COM_EMUNDUS_POLL_RUN_FIELD_LABEL',
    'COM_EMUNDUS_POLL_RUN_NOTIFY',
    'COM_EMUNDUS_POLL_RUN_OPEN',
    'COM_EMUNDUS_POLL_RUN_SENDING',
    'COM_EMUNDUS_POLLS_EXPORTS_EXCEL',
    'COM_EMUNDUS_ONBOARD_ACTION_CONTACT_PARTICIPANTS',
    'COM_EMUNDUS_POLL_CONTACT_PARTICIPANTS_LABEL',
    'COM_EMUNDUS_POLL_CONTACT_PARTICIPANTS_SEND',
    'COM_EMUNDUS_POLL_CONTACT_PARTICIPANTS_SENDING',
    'COM_EMUNDUS_POLLS_CLOSE',
    'COM_EMUNDUS_POLL_CLOSE_TITLE',
    'COM_EMUNDUS_POLL_CLOSE_FIELD_LABEL',
    'COM_EMUNDUS_POLL_CLOSE_NOTIFY',
    'COM_EMUNDUS_POLL_CLOSE_SENDING',
    'COM_EMUNDUS_POLL_CLOSE_BUTTON',
    'COM_EMUNDUS_POLLS_DELETE',
    'COM_EMUNDUS_REGISTRANTS_FILE_READY',
    'COM_EMUNDUS_POLL_SHOW_SLOT_DETAILS',
    'COM_EMUNDUS_POLLS_DELETE_TITLE',
    'COM_EMUNDUS_POLLS_DELETE_CONFIRM_BUTTON',
    'COM_EMUNDUS_POLLS_DELETE_CANCEL_BUTTON',
    'COM_EMUNDUS_POLL_REPLY_SEND_ANSWERS',
    'COM_EMUNDUS_POLL_ANSWERS_SENDED_LOCKED',
    'COM_EMUNDUS_POLL_ANSWERS_HELP',
    'COM_EMUNDUS_POLL_REPLY_MODAL_TITLE',
    'COM_EMUNDUS_POLL_RESEND_SUCCESS',
];
foreach ($translations as $translation) {
    Text::script($translation);
}

$data = LayoutFactory::prepareVueData();

$user = Factory::getApplication()->getIdentity();

$actionRepository = new ActionRepository();
$pollAction   = $actionRepository->getByName('poll');

$data['crud'] = [
	'poll' => [
		'c' => $data['coordinator_access'] || $data['sysadmin_access'] || EmundusHelperAccess::asAccessAction($pollAction->getId(), 'c', $user->id),
		'r' => $data['coordinator_access'] || $data['sysadmin_access'] || EmundusHelperAccess::asAccessAction($pollAction->getId(), 'r', $user->id),
		'u' => $data['coordinator_access'] || $data['sysadmin_access'] || EmundusHelperAccess::asAccessAction($pollAction->getId(), 'u', $user->id),
		'd' => $data['coordinator_access'] || $data['sysadmin_access'] || EmundusHelperAccess::asAccessAction($pollAction->getId(), 'd', $user->id),
	],
];

echo LayoutHelper::render('emundus.vue-mount', [
    'component' => 'Polls/Polls',
    'data'      => $data,
]);
?>