<?php

use Joomla\CMS\Factory;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Layout\LayoutHelper;
use Tchooz\Factories\LayoutFactory;
use Tchooz\Repositories\Actions\ActionRepository;

$translations = [
	'COM_EMUNDUS_RESOURCES_TITLE',
	'COM_EMUNDUS_RESOURCES_INTRO',
	'COM_EMUNDUS_RESOURCES_ADD_FOLDER',
	'COM_EMUNDUS_RESOURCES_ADD_FOLDER_INPUT_LABEL',
	'COM_EMUNDUS_RESOURCES_ADD_FOLDER_CONFIRM_BUTTON',
	'COM_EMUNDUS_RESOURCES_IMPORT_DOCUMENT',
	'COM_EMUNDUS_RESOURCES_NO_RESULTS',
	'COM_EMUNDUS_RESOURCES_IMPORT_DROPZONE',
	'COM_EMUNDUS_RESOURCES_IMPORT_CONFIRM',
	'COM_EMUNDUS_RESOURCES_IMPORT_SUCCESS',
	'COM_EMUNDUS_RESOURCES_IMPORT_ERROR',
	'COM_EMUNDUS_RESOURCES_PREVIEW_LOADING',
	'COM_EMUNDUS_RESOURCES_PREVIEW_ERROR',
	'COM_EMUNDUS_RESOURCES_PREVIEW_DOWNLOAD',
	'COM_EMUNDUS_RESOURCES_PREVIEW_PREVIOUS',
	'COM_EMUNDUS_RESOURCES_PREVIEW_NEXT',
	'COM_EMUNDUS_RESOURCES_ACTION_DOWNLOAD',
	'COM_EMUNDUS_RESOURCES_ACTION_DOWNLOAD_ARCHIVE',
	'COM_EMUNDUS_RESOURCES_ACTION_RENAME',
	'COM_EMUNDUS_RESOURCES_RENAME_FOLDER_INPUT_LABEL',
	'COM_EMUNDUS_RESOURCES_RENAME_FILE_INPUT_LABEL',
	'COM_EMUNDUS_RESOURCES_RENAME_FOLDER_CONFIRM_BUTTON',
	'COM_EMUNDUS_RESOURCES_RENAME_FILE_CONFIRM_BUTTON',
	'COM_EMUNDUS_RESOURCES_ACTION_MOVE',
	'COM_EMUNDUS_RESOURCES_MOVE_INPUT_LABEL',
	'COM_EMUNDUS_RESOURCES_MOVE_CONFIRM_BUTTON',
	'COM_EMUNDUS_RESOURCES_MOVE_ROOT',
	'COM_EMUNDUS_RESOURCES_ACTION_DELETE',
	'COM_EMUNDUS_RESOURCES_DELETE_FOLDER_CONFIRM',
	'COM_EMUNDUS_RESOURCES_DELETE_FILE_CONFIRM',
	'COM_EMUNDUS_RESOURCES_ACTION_DELETE_FOLDER_CONFIRM_LABEL',
	'COM_EMUNDUS_RESOURCES_ACTION_DELETE_FILE_CONFIRM_LABEL',
	'COM_EMUNDUS_RESOURCES_DELETE_CONFIRM_BUTTON',
	'COM_EMUNDUS_RESOURCES_DELETE_CANCEL_BUTTON',
	'COM_EMUNDUS_RESOURCES_ROOT',
	'COM_EMUNDUS_ONBOARD_LABEL_RESOURCE',
	// Access & sharing modal
	'COM_EMUNDUS_RESOURCE_ACCESS_TITLE',
	'COM_EMUNDUS_RESOURCE_ACCESS_TAB_ROLES',
	'COM_EMUNDUS_RESOURCE_ACCESS_TAB_SPACES',
	'COM_EMUNDUS_RESOURCE_ACCESS_TAB_SHARE',
	'COM_EMUNDUS_RESOURCE_ACCESS_ROLES',
	'COM_EMUNDUS_RESOURCE_ACCESS_GROUPS',
	'COM_EMUNDUS_RESOURCE_ACCESS_USERS',
	'COM_EMUNDUS_RESOURCE_ACCESS_ADD_ROLE',
	'COM_EMUNDUS_RESOURCE_ACCESS_ADD_GROUP',
	'COM_EMUNDUS_RESOURCE_ACCESS_ADD_USER',
	'COM_EMUNDUS_RESOURCE_ACCESS_NO_OPTION',
	'COM_EMUNDUS_RESOURCE_ACCESS_SAVED',
	'COM_EMUNDUS_RESOURCE_ACCESS_SAVE_ERROR',
	'COM_EMUNDUS_RESOURCE_PERMISSION_VIEW',
	'COM_EMUNDUS_RESOURCE_PERMISSION_EDIT',
	'COM_EMUNDUS_RESOURCE_PERMISSION_MANAGE',
	'COM_EMUNDUS_RESOURCE_SHARE_EXPIRATION',
	'COM_EMUNDUS_RESOURCE_SHARE_PASSWORD',
	'COM_EMUNDUS_RESOURCE_SHARE_PASSWORD_PLACEHOLDER',
	'COM_EMUNDUS_RESOURCE_SHARE_PASSWORD_SET',
	'COM_EMUNDUS_RESOURCE_SHARE_CODE',
	'COM_EMUNDUS_RESOURCE_SHARE_CODE_HINT',
	'COM_EMUNDUS_RESOURCE_SHARE_CODE_COPIED',
	'COM_EMUNDUS_RESOURCE_SHARE_CODE_COPY_ERROR',
	'COM_EMUNDUS_RESOURCE_SHARE_REVOKE',
	'COM_EMUNDUS_RESOURCE_SHARE_REVOKED',
	'COM_EMUNDUS_RESOURCE_SHARE_REVOKE_ERROR',
	'COM_EMUNDUS_RESOURCE_SHARE_SAVE_ERROR',
	'COM_EMUNDUS_RESOURCE_SHARE_SAVE',
	'COM_EMUNDUS_SAVE',
	'COM_EMUNDUS_CLOSE',
	'COM_EMUNDUS_COPY',
	'COM_EMUNDUS_CONFIRM',
	'COM_EMUNDUS_CANCEL',
	'COM_EMUNDUS_DELETE',
	'COM_EMUNDUS_RESOURCES_FILTER_TYPE',
	'COM_EMUNDUS_RESOURCES_FILTER_TYPE_ALL',
	'COM_EMUNDUS_RESOURCES_FILTER_TYPE_FILE',
	'COM_EMUNDUS_RESOURCES_FILTER_TYPE_FOLDER',
	'COM_EMUNDUS_RESOURCES_FILTER_FORMAT_ALL',
	'COM_EMUNDUS_RESOURCES_FILTER_FORMAT',
	'COM_EMUNDUS_RESOURCE_ACCESS_FOLDER_TITLE',
	'COM_EMUNDUS_RESOURCES_IMPORT_TARGET_FOLDER',
	'COM_EMUNDUS_RESOURCES_IMPORT_ERROR_FILESIZE',
	'COM_EMUNDUS_REGISTRANTS_FILE_READY',
	'COM_EMUNDUS_RESOURCES_IMPORT_DOCUMENT_LABEL',
	'COM_EMUNDUS_RESOURCES_IMPORT_DOCUMENT_HELPTEXT',
];
foreach ($translations as $translation) {
	Text::script($translation);
}

$data = LayoutFactory::prepareVueData();

$user = Factory::getApplication()->getIdentity();

$actionRepository = new ActionRepository();
$resourceAction   = $actionRepository->getByName('resource');

$data['crud'] = [
	'resource' => [
		'c' => $data['coordinator_access'] || $data['sysadmin_access'] || EmundusHelperAccess::asAccessAction($resourceAction->getId(), 'c', $user->id),
		'r' => $data['coordinator_access'] || $data['sysadmin_access'] || EmundusHelperAccess::asAccessAction($resourceAction->getId(), 'r', $user->id),
		'u' => $data['coordinator_access'] || $data['sysadmin_access'] || EmundusHelperAccess::asAccessAction($resourceAction->getId(), 'u', $user->id),
		'd' => $data['coordinator_access'] || $data['sysadmin_access'] || EmundusHelperAccess::asAccessAction($resourceAction->getId(), 'd', $user->id),
	],
];

$data['intro'] = '';
$emundusUser = Factory::getApplication()->getSession()->get('emundusUser');
if($emundusUser->applicant !== 1)
{
	$data['intro'] = 'COM_EMUNDUS_RESOURCES_INTRO';
}

echo LayoutHelper::render('emundus.vue-mount', [
	'component' => 'Resources/Resources',
	'data'      => $data,
]);

