<?php
/**
 * @package     Joomla
 * @subpackage  com_emundus
 *
 * @copyright   Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

// No direct access to this file
defined('_JEXEC') or die('Restricted Access');

use Joomla\CMS\Factory;
use Joomla\CMS\Language\Text;
use Tchooz\Factories\LayoutFactory;
use Tchooz\Repositories\Actions\ActionRepository;

require_once(JPATH_ROOT . '/components/com_emundus/helpers/access.php');

Text::script('COM_EMUNDUS_ONBOARD_MODIFY');
Text::script('COM_EMUNDUS_ONBOARD_CRC');
Text::script('COM_EMUNDUS_ONBOARD_CRC_INTRO');
Text::script('COM_EMUNDUS_ONBOARD_LABEL_CONTACTS');
Text::script('COM_EMUNDUS_ONBOARD_CRC_INTRO');
Text::script('COM_EMUNDUS_ONBOARD_CRC_CONTACTS');
Text::script('COM_EMUNDUS_ONBOARD_NOCONTACTS');
Text::script('COM_EMUNDUS_ONBOARD_ADD_CONTACT');
Text::script('COM_EMUNDUS_ONBOARD_CRC_CONTACT_EMAIL');
Text::script('COM_EMUNDUS_ONBOARD_CRC_CONTACT_PHONENUMBER');
Text::script('COM_EMUNDUS_ONBOARD_CRC_CONTACT_STATUS');
Text::script('COM_EMUNDUS_ONBOARD_CONTACT_DELETE');
Text::script('COM_EMUNDUS_ONBOARD_ORGANIZATIONS');
Text::script('COM_EMUNDUS_ONBOARD_NOORGANIZATIONS');
Text::script('COM_EMUNDUS_ONBOARD_CONTACT_FILTER_PUBLISH');
Text::script('COM_EMUNDUS_ONBOARD_CONTACT_FILTER_NAME');
Text::script('COM_EMUNDUS_ONBOARD_CONTACT_FILTER_PHONE_NUMBER');
Text::script('COM_EMUNDUS_ONBOARD_CONTACT_FILTER_NO_PHONE_NUMBER');
Text::script('COM_EMUNDUS_ONBOARD_CONTACT_FILTER_ORGANIZATION');
Text::script('COM_EMUNDUS_ONBOARD_ORG_FILTER_NO_ORGANIZATION');
Text::script('COM_EMUNDUS_ONBOARD_CONTACT_FILTER_NATIONALITY');
Text::script('COM_EMUNDUS_ONBOARD_CONTACT_FILTER_NO_NATIONALITY');
Text::script('COM_EMUNDUS_SETTINGS_INTEGRATION_COUNTRIES_LIST');
Text::script('COM_EMUNDUS_ONBOARD_FILTER_ALL');
Text::script('COM_EMUNDUS_ONBOARD_FILTER_PUBLISH');
Text::script('COM_EMUNDUS_ONBOARD_FILTER_UNPUBLISH');
Text::script('COM_EMUNDUS_ONBOARD_ACTION_UNPUBLISH');
Text::script('COM_EMUNDUS_ONBOARD_ACTION_PUBLISH');
Text::script('COM_EMUNDUS_ONBOARD_ACTION_DUPLICATE');
Text::script('COM_EMUNDUS_ONBOARD_ADD_ORGANIZATION');
Text::script('COM_EMUNDUS_ONBOARD_ORG_DELETE');
Text::script('COM_EMUNDUS_ONBOARD_ORGS_ASSOCIATED');
Text::script('COM_EMUNDUS_ONBOARD_ORGS_ASSOCIATED_TITLE');
Text::script('COM_EMUNDUS_ONBOARD_ORGS_ASSOCIATED_NOT');
Text::script('COM_EMUNDUS_ONBOARD_ORG_FILTER_NAME');
Text::script('COM_EMUNDUS_ONBOARD_ORG_FILTER_IDENTIFIER');
Text::script('COM_EMUNDUS_ONBOARD_ORG_FILTER_NO_IDENTIFIER_CODE');
Text::script('COM_EMUNDUS_ONBOARD_CONTACTS_EXPORTS_EXCEL');
Text::script('COM_EMUNDUS_ONBOARD_CONTACTS_PUBLISHED');
Text::script('COM_EMUNDUS_ONBOARD_CONTACTS_UNPUBLISHED');
Text::script('COM_EMUNDUS_ONBOARD_CONTACTS_STATUS');
Text::script('COM_EMUNDUS_ONBOARD_ACTION_CRC_SHOW_DETAILS');
Text::script('COM_EMUNDUS_ONBOARD_ADRESSE');
Text::script('COM_EMUNDUS_ONBOARD_ADD_CONTACT_DEPARTMENT');
Text::script('COM_EMUNDUS_ONBOARD_ADD_CONTACT_ROLE');
Text::script('COM_EMUNDUS_ONBOARD_ADD_CONTACT_FILES');
Text::script('COM_EMUNDUS_ONBOARD_ADD_CONTACT_FILES_CONSULT');
Text::script('COM_EMUNDUS_ONBOARD_ADD_CONTACT_ORGANIZATIONS');
Text::script('COM_EMUNDUS_ONBOARD_ADD_CONTACT_GENDER');
Text::script('COM_EMUNDUS_ONBOARD_ADD_CONTACT_BIRTHDATE');
Text::script('COM_EMUNDUS_ONBOARD_ADD_CONTACT_COUNTRIES');
Text::script('COM_EMUNDUS_ONBOARD_ADD_CONTACT_AGE');
Text::script('COM_EMUNDUS_ONBOARD_ADD_CONTACT_BIRTH');
Text::script('COM_EMUNDUS_ONBOARD_ADD_ORG_DESCRIPTION');
Text::script('COM_EMUNDUS_ONBOARD_ADD_ORG_CONTACT');
Text::script('COM_EMUNDUS_ONBOARD_ADD_ORG_OTHER_CONTACT');
Text::script('COM_EMUNDUS_REGISTRANTS_FILE_READY');
Text::script('COM_EMUNDUS_URL_UNVERIFIED_AND_UNSECURED');
Text::script('COM_EMUNDUS_ONBOARD_ADD_ORG_FILES');
Text::script('COM_EMUNDUS_ONBOARD_ADD_ORG_FILES_CONSULT');
Text::script('COM_EMUNDUS_ONBOARD_UPDATE_CONTACT_FILES');
Text::script('COM_EMUNDUS_ONBOARD_UPDATE_ORGANIZATION_FILES');
Text::script('COM_EMUNDUS_ONBOARD_CRC_UPDATE_CONTACT_FILES_ASSOCIATED');
Text::script('COM_EMUNDUS_ONBOARD_CRC_UPDATE_ORGANIZATION_FILES_ASSOCIATED');
Text::script('COM_EMUNDUS_ONBOARD_CRC_UPDATE_CONTACT_FILES_ASSOCIATED_PLACEHOLDER');
Text::script('COM_EMUNDUS_ONBOARD_CRC_UPDATE_ORGANIZATION_FILES_ASSOCIATED_PLACEHOLDER');
Text::script('COM_EMUNDUS_ONBOARD_REGISTRANT_EDIT_CANCEL');
Text::script('COM_EMUNDUS_ONBOARD_CRC_UPDATE_CONTACT_FILES_ASSOCIATED_CANCEL');
Text::script('COM_EMUNDUS_ONBOARD_CRC_UPDATE_ORGANIZATION_FILES_ASSOCIATED_CANCEL');
Text::script('COM_EMUNDUS_ONBOARD_CRC_UPDATE_CONTACT_FILES_ASSOCIATED_CONFIRM');
Text::script('COM_EMUNDUS_ONBOARD_CRC_UPDATE_ORGANIZATION_FILES_ASSOCIATED_CONFIRM');
Text::script('COM_EMUNDUS_ONBOARD_CRC_UPDATE_CONTACT_FILES_ASSOCIATED_TITLE');
Text::script('COM_EMUNDUS_ONBOARD_CRC_UPDATE_ORGANIZATION_FILES_ASSOCIATED_TITLE');
Text::script('COM_EMUNDUS_ONBOARD_CRC_UPDATE_CONTACT_FILES_SUCCESS');
Text::script('COM_EMUNDUS_ONBOARD_CRC_UPDATE_ORGANIZATION_FILES_SUCCESS');
Text::script('COM_EMUNDUS_ONBOARD_CRC_UPDATE_CONTACT_FILES_FAILED');
Text::script('COM_EMUNDUS_ONBOARD_CRC_UPDATE_ORGANIZATION_FILES_FAILED');



Text::script('COM_EMUNDUS_IMPORT_TITLE');
Text::script('COM_EMUNDUS_IMPORT_FIELDS_INTRO');
Text::script('COM_EMUNDUS_IMPORT_FIELDS_HELP_TITLE');
Text::script('COM_EMUNDUS_IMPORT_VIEW_ACCEPTED_COLUMNS');
Text::script('COM_EMUNDUS_IMPORT_ACCEPTED_COLUMNS');
Text::script('COM_EMUNDUS_IMPORT_REQUIRED_LEGEND');
Text::script('COM_EMUNDUS_IMPORT_DROP_FILE_HERE');
Text::script('COM_EMUNDUS_IMPORT_ACCEPTED_FORMATS');
Text::script('COM_EMUNDUS_IMPORT_ANALYZING');
Text::script('COM_EMUNDUS_IMPORT_UPLOAD_ERROR');

Text::script('COM_EMUNDUS_IMPORT_UNSUPPORTED_FORMAT');
Text::script('COM_EMUNDUS_IMPORT_MISSING_REQUIRED_COLUMNS');
Text::script('COM_EMUNDUS_IMPORT_ALL_REQUIRED_FOUND');
Text::script('COM_EMUNDUS_IMPORT_FILE_COLUMN');
Text::script('COM_EMUNDUS_IMPORT_COLUMN_IGNORED');
Text::script('COM_EMUNDUS_IMPORT_UPLOAD_ANOTHER');
Text::script('COM_EMUNDUS_IMPORT_CONFIRM');
Text::script('COM_EMUNDUS_IMPORT_CONTACT_INVALID_GENDER');
Text::script('COM_EMUNDUS_IMPORT_CONTACT_INVALID_BIRTHDATE');
Text::script('COM_EMUNDUS_IMPORT_CONTACT_INVALID_COUNTRY_CODE');
Text::script('COM_EMUNDUS_IMPORT_DRY_RUN_TITLE');
Text::script('COM_EMUNDUS_IMPORT_RUNNING');
Text::script('COM_EMUNDUS_IMPORT_ROWS_CREATED');
Text::script('COM_EMUNDUS_IMPORT_ROWS_SKIPPED');
Text::script('COM_EMUNDUS_IMPORT_ROWS_FAILED');
Text::script('COM_EMUNDUS_IMPORT_ERRORS_TITLE');
Text::script('COM_EMUNDUS_IMPORT_ROW_NUMBER');
Text::script('COM_EMUNDUS_IMPORT_SUCCESS_TITLE');
Text::script('COM_EMUNDUS_IMPORT_LAUNCH');
Text::script('COM_EMUNDUS_ACTIONS_BACK');
Text::script('COM_EMUNDUS_IMPORT_NOTHING_TO_CREATE');
Text::script('COM_EMUNDUS_IMPORT_BACK');
Text::script('COM_EMUNDUS_IMPORT_BACK_TO_UPLOAD');
Text::script('COM_EMUNDUS_IMPORT_FIELDS_HELP_INTRO');
Text::script('COM_EMUNDUS_IMPORT_BROWSE');
Text::script('COM_EMUNDUS_IMPORT_REPORT_TITLE');
Text::script('COM_EMUNDUS_IMPORT_ROWS_TO_BE_CREATED');
Text::script('COM_EMUNDUS_IMPORT_ROWS_CREATED');
Text::script('COM_EMUNDUS_IMPORT_ROWS_TO_BE_UPDATED');
Text::script('COM_EMUNDUS_IMPORT_ROWS_UPDATED');
Text::script('COM_EMUNDUS_IMPORT_STATUS_SKIPPED');
Text::script('COM_EMUNDUS_IMPORT_STATUS_FAILED');
Text::script('COM_EMUNDUS_IMPORT_STATUS_FINISH');
Text::script('COM_EMUNDUS_IMPORT_DRY_RESULT');
Text::script('COM_EMUNDUS_IMPORT_IMPORT_RESULT');
Text::script('COM_EMUNDUS_ONBOARD_ACTION_IMPORT_CONTACTS');
Text::script('COM_EMUNDUS_ONBOARD_ACTION_IMPORT_ORGANIZATIONS');
Text::script('COM_EMUNDUS_IMPORT_DOWNLOAD_XLSX');
Text::script('COM_EMUNDUS_IMPORT_MODEL_DOC_DATA_NAME');
Text::script('COM_EMUNDUS_IMPORT_ALLOWED_HEADER');
Text::script('COM_EMUNDUS_IMPORT_MODEL_DOC_FORMAT');
Text::script('COM_EMUNDUS_IMPORT_MODEL_DOC_EXAMPLES');
Text::script('COM_EMUNDUS_IMPORT_MODEL_DOC_REQUIRED_VALUE');
Text::script('COM_EMUNDUS_IMPORT_REQUIRED_VALUE');
Text::script('COM_EMUNDUS_IMPORT_UNKNOWN_HEADERS_WARNING');
Text::script('COM_EMUNDUS_IMPORT_CONFLICT_MODE_LABEL');
Text::script('COM_EMUNDUS_IMPORT_CONFLICT_MODE_SKIP');
Text::script('COM_EMUNDUS_IMPORT_CONFLICT_MODE_UPDATE');
Text::script('COM_EMUNDUS_IMPORT_CONFLICT_MODE_CREATE_NEW');
Text::script('COM_EMUNDUS_IMPORT_LAUNCH_DRY_RUN');
Text::script('COM_EMUNDUS_IMPORT_FILE_READY');
Text::script('COM_EMUNDUS_IMPORT_ENTITY_CONTACT');
Text::script('COM_EMUNDUS_IMPORT_ENTITY_ORGANIZATION');
Text::script('COM_EMUNDUS_IMPORT_SUMMARY_TO_BE_CREATED');
Text::script('COM_EMUNDUS_IMPORT_SUMMARY_CREATED');
Text::script('COM_EMUNDUS_IMPORT_SUMMARY_TO_BE_UPDATED');
Text::script('COM_EMUNDUS_IMPORT_SUMMARY_UPDATED');
Text::script('COM_EMUNDUS_IMPORT_SUMMARY_SKIPPED');
Text::script('COM_EMUNDUS_IMPORT_SUMMARY_FAILED_ONE_ELEMENT');
Text::script('COM_EMUNDUS_IMPORT_SUMMARY_FAILED_SEVERAL_ELEMENTS');
Text::script('COM_EMUNDUS_IMPORT_DRY_RESULT_TITLE');
Text::script('COM_EMUNDUS_IMPORT_RESULT');
Text::script('COM_EMUNDUS_ONBOARD_ADD_CONTACT_ADDRESS_DESCRIPTION');
Text::script('COM_EMUNDUS_ONBOARD_ADD_CONTACT_ADDRESS_DESCRIPTION_HELP');
Text::script('COM_EMUNDUS_ONBOARD_CRC_TAB_COMMENTS');
Text::script('COM_EMUNDUS_ONBOARD_CRC_TAB_INFORMATIONS');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_ADD');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_LABEL');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_PLACEHOLDER');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_VISIBILITY');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_VISIBILITY_PUBLIC');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_VISIBILITY_PRIVATE');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_DELETED_PLACEHOLDER');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_SUBMIT');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_EDIT_SUBMIT');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_CANCEL');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_DATE_AT');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_REPLIES');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_REPLYING_TO');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_EDITING');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_DELETE');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_REPLY');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_CANCEL_REPLY');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_EDITED');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_EDIT');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENTS_PLACEHOLDER');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_SEARCH_PLACEHOLDER');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_SEARCH_NO_RESULTS');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_SAVE_SUCCESS');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_SAVE_ERROR');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_UPDATE_SUCCESS');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_CANCEL_EDIT');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_DELETE_CONFIRM_TITLE');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_DELETE_CONFIRM_TEXT');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_DELETE_SUCCESS');
Text::script('COM_EMUNDUS_ONBOARD_CRC_COMMENT_DELETE_ERROR');

$data = LayoutFactory::prepareVueData();

$user = Factory::getApplication()->getIdentity();

$actionRepository = new ActionRepository();
$contactAction    = $actionRepository->getByName('contact');
$orgAction        = $actionRepository->getByName('organization');

$data['crud'] = [
    'contact'      => [
        'c' => $data['coordinator_access'] || $data['sysadmin_access'] || EmundusHelperAccess::asAccessAction($contactAction->getId(), 'c', $user->id),
        'r' => $data['coordinator_access'] || $data['sysadmin_access'] || EmundusHelperAccess::asAccessAction($contactAction->getId(), 'r', $user->id),
        'u' => $data['coordinator_access'] || $data['sysadmin_access'] || EmundusHelperAccess::asAccessAction($contactAction->getId(), 'u', $user->id),
        'd' => $data['coordinator_access'] || $data['sysadmin_access'] || EmundusHelperAccess::asAccessAction($contactAction->getId(), 'd', $user->id),
    ],
    'organization' => [
        'c' => $data['coordinator_access'] || $data['sysadmin_access'] || EmundusHelperAccess::asAccessAction($orgAction->getId(), 'c', $user->id),
        'r' => $data['coordinator_access'] || $data['sysadmin_access'] || EmundusHelperAccess::asAccessAction($orgAction->getId(), 'r', $user->id),
        'u' => $data['coordinator_access'] || $data['sysadmin_access'] || EmundusHelperAccess::asAccessAction($orgAction->getId(), 'u', $user->id),
        'd' => $data['coordinator_access'] || $data['sysadmin_access'] || EmundusHelperAccess::asAccessAction($orgAction->getId(), 'd', $user->id),
    ],
];

$datas = [
    'shortLang'       => $data['short_lang'],
    'currentLanguage' => $data['current_lang'],
    'defaultLang'     => $data['default_lang'],
    'manyLanguages'   => $data['many_languages'],
    'crud'            => $data['crud'],
];
?>

<div id="em-component-vue"
     component="Crc"
     data="<?= htmlspecialchars(json_encode($datas), ENT_QUOTES, 'UTF-8'); ?>"
>
</div>

<script type="module" src="media/com_emundus_vue/app_emundus.js?<?php echo $data['hash'] ?>"></script>
