<?php
/**
 * @package     Tchooz\Factories\Language
 * @subpackage
 *
 * @copyright   A copyright
 * @license     A "Slug" license name e.g. GPL2
 */

namespace Tchooz\Services\Language;

use Joomla\CMS\Cache\CacheControllerFactoryInterface;
use Joomla\CMS\Factory;
use Joomla\CMS\Language\Language;
use Joomla\CMS\Language\LanguageHelper;
use Joomla\CMS\User\UserFactoryInterface;
use Tchooz\Entities\Language\LanguageEntity;
use Tchooz\Enums\StatusEnum;
use Tchooz\Factories\Language\LanguageFactory;
use Tchooz\Repositories\Language\LanguageRepository;
use Tchooz\Traits\TraitAutomatedTask;

class DbLanguage extends Language
{
	use TraitAutomatedTask;

	private LanguageRepository $languageRepository;

	public function __construct($lang = null, $debug = false, Language $existing = null)
	{
		if (is_null($lang))
		{
			$lang = Factory::getApplication()->getLanguage()->getTag();
		}

		// Load from database here
		$this->languageRepository = new LanguageRepository();
		$this->languageRepository->setLangCode($lang);

		parent::__construct($lang, $debug);

		if ($existing instanceof Language)
		{
			// copy existing loaded strings
			$this->strings        = array_merge($this->strings, $existing->strings);
			$this->strings        = array_unique($this->strings);
			$this->debug          = $existing->debug;
			$this->paths          = $existing->paths;
			$this->override       = $existing->override;
			$this->transliterator = $existing->transliterator;
			$this->locale         = $existing->locale;
			$this->lang           = $lang;
			$this->catalogue      = $existing->catalogue;
			$this->basePath       = $existing->basePath;
			$this->helper         = $existing->helper;
			$this->localise       = $existing->localise;
			$this->metadata       = $existing->metadata;
			$this->default        = $existing->default;
			$this->orphans        = $existing->orphans;
		}

		// Need to reload Joomla language to have the core + extensions translations
		$this->load('joomla', JPATH_BASE, $lang, true);

		// Do not load entities here to avoid performance issues
		$emundusLanguages = $this->languageRepository->getAll(['lang_code' => $lang], true, 0, 0, false);
		foreach ($emundusLanguages as $language)
		{
			$this->strings[$language->tag] = $language->override;
		}

		$this->override = array_replace($this->override, $this->strings);
	}

	public function load($extension = 'joomla', $basePath = JPATH_BASE, $lang = null, $reload = false, $default = true)
	{
		return parent::load($extension, $basePath, $lang, $reload, $default); // TODO: Change the autogenerated stub
	}

	public function addTranslation($key, $value): void
	{
		$this->strings[$key]  = $value;
		$this->override[$key] = $value;
	}

	public function replaceAccents($value): string
	{
		$unwanted_array = array('Š' => 'S', 'š' => 's', 'Ž' => 'Z', 'ž' => 'z', 'À' => 'A', 'Á' => 'A', 'Â' => 'A', 'Ã' => 'A', 'Ä' => 'A', 'Å' => 'A', 'Æ' => 'A', 'Ç' => 'C', 'È' => 'E', 'É' => 'E',
		                        'Ê' => 'E', 'Ë' => 'E', 'Ì' => 'I', 'Í' => 'I', 'Î' => 'I', 'Ï' => 'I', 'Ñ' => 'N', 'Ò' => 'O', 'Ó' => 'O', 'Ô' => 'O', 'Õ' => 'O', 'Ö' => 'O', 'Ø' => 'O', 'Ù' => 'U',
		                        'Ú' => 'U', 'Û' => 'U', 'Ü' => 'U', 'Ý' => 'Y', 'Þ' => 'B', 'ß' => 'Ss', 'à' => 'a', 'á' => 'a', 'â' => 'a', 'ã' => 'a', 'ä' => 'a', 'å' => 'a', 'æ' => 'a', 'ç' => 'c',
		                        'è' => 'e', 'é' => 'e', 'ê' => 'e', 'ë' => 'e', 'ì' => 'i', 'í' => 'i', 'î' => 'i', 'ï' => 'i', 'ð' => 'o', 'ñ' => 'n', 'ò' => 'o', 'ó' => 'o', 'ô' => 'o', 'õ' => 'o',
		                        'ö' => 'o', 'ø' => 'o', 'ù' => 'u', 'ú' => 'u', 'û' => 'u', 'ý' => 'y', 'þ' => 'b', 'ÿ' => 'y', '!' => '', '?' => '', '*' => '', '%' => 'y', '^' => '', '€' => '', '+' => '', '=' => '',
		                        ';' => '', ',' => '', '&' => '', '@' => '', '#' => '', '`' => '', '¨' => '', '§' => '', '"' => '', '\'' => '', '\\' => '', '/' => '', '(' => '', ')' => '', '[' => '', ']' => '', ' ' => '_');

		return strtr($value, $unwanted_array);
	}

	public function filesToDatabase(): bool
	{
		$results = [];

		try
		{
			$now = new \DateTime();

			$automatedUser = $this->getAutomatedTaskUser();

			$platformLanguages = $this->languageRepository->getPlatformLanguages();

			$files = $this->getLanguageFiles($platformLanguages);

			if (Factory::getApplication()->isClient('cli'))
			{
				$length = 0;
				$index  = 0;
				foreach ($files as $file)
				{
					$parsed_file = LanguageHelper::parseIniFile($file);
					$length      += sizeof($parsed_file);
				}
			}

			if(Factory::getApplication()->isClient('cli'))
			{
				echo "\r\033[33mImporting language files to database... \033[0m\n";
			}

			foreach ($files as $file)
			{
				$parsed_file = LanguageHelper::parseIniFile($file);

				$file      = explode('/', $file);
				$file_name = end($file);
				$language  = strtok($file_name, '.');

				foreach ($parsed_file as $key => $val)
				{
					if (isset($index) && isset($length) && Factory::getApplication()->isClient('cli'))
					{
						$index++;
						echo "\r\033[33m$index/$length translations backed \033[0m";
					}

					$this->languageRepository->setLangCode($language);

					$exist = $this->languageRepository->getByTag($key);
					if (empty($exist))
					{
						$references = $this->languageRepository->findReferences($key);

						$languageEntity = new LanguageEntity(
							tag: $key,
							langCode: $language,
							override: $val,
							originalText: $val,
							type: 'override',
							createdBy: $automatedUser,
							createdDate: $now,
							referenceId: $references['reference_id'],
							referenceTable: $references['reference_table'],
							referenceField: $references['reference_field'],
						);

						$results[] = $this->languageRepository->flush($languageEntity);
					}
					else
					{
						// If value is different, update it
						if ($exist->getOverrideMd5() !== md5($val))
						{
							$exist->setOverride($val);
							$exist->setModifiedBy($automatedUser);
							$exist->setModifiedDate($now);

							$results[] = $this->languageRepository->flush($exist);
						}
					}
				}
			}
		}
		catch (\Exception $e)
		{
			throw new \RuntimeException('Failed to import language files to database: ' . $e->getMessage(), 0, $e);
		}

		if(Factory::getApplication()->isClient('cli'))
		{
			echo "\n";
		}

		return !in_array(false, $results, true);
	}

	public function databaseToFiles(): bool
	{
		$results           = [];
		$platformLanguages = $this->languageRepository->getPlatformLanguages();

		if (!empty($platformLanguages))
		{
			try
			{
				foreach ($platformLanguages as $language)
				{
					$this->languageRepository->setLangCode($language);

					$overrideFile = JPATH_SITE . '/language/overrides/' . $language . '.override.ini';
					if (file_exists($overrideFile))
					{
						$filters            = [
							'type' => 'override',
						];
						$modified_overrides = $this->languageRepository->getAll($filters);

						if (!empty($modified_overrides))
						{
							$parsed_file = LanguageHelper::parseIniFile($overrideFile);
							foreach ($modified_overrides as $modified_override)
							{
								if ($modified_override->getPublished() === StatusEnum::TRASHED)
								{
									// Remove it from the file
									unset($parsed_file[$modified_override->getTag()]);

									$this->languageRepository->delete($modified_override->getId());
									continue;
								}

								$parsed_file[$modified_override->getTag()] = $modified_override->getOverride();
							}

							$results[] = LanguageHelper::saveToIniFile($overrideFile, $parsed_file);
						}
					}
				}
			}
			catch (\Exception $e)
			{
				throw new \RuntimeException('Failed to export language files from database: ' . $e->getMessage(), 0, $e);
			}
		}
		else
		{
			throw new \RuntimeException('No platform languages found to export language files from database.');
		}

		return !in_array(false, $results, true);
	}

	public function repairOrphans(): bool
	{
		$result = [];

		// Repair orphans of other languages than the main one
		try
		{
			$defaultLanguage   = LanguageFactory::getDefaultLanguageCode();
			$platformLanguages = $this->languageRepository->getPlatformLanguages();

			// Remove default language from the list
			$otherLanguages = array_filter($platformLanguages, function ($lang) use ($defaultLanguage) {
				return $lang !== $defaultLanguage;
			});

			if (!empty($otherLanguages))
			{
				echo "Repairing orphan language entries...\n";

				// Get all translations of defaultLanguage
				$mainTranslations = $this->languageRepository->getAll(['lang_code' => $defaultLanguage], false, 0, 0, false);

				foreach ($otherLanguages as $language)
				{
					$index = 0;
					$this->languageRepository->setLangCode($language);

					foreach ($mainTranslations as $translation)
					{
						$exist = $this->languageRepository->getByTag($translation->tag);
						if (empty($exist))
						{
							$creator = !empty($translation->created_by) ? Factory::getContainer()->get(UserFactoryInterface::class)->loadUserById($translation->created_by) : null;

							$languageEntity = new LanguageEntity(
								tag: $translation->tag,
								langCode: $language,
								override: $translation->override,
								originalText: $translation->original_text,
								type: 'override',
								createdBy: !empty($creator) ? $creator : null,
								createdDate: (!empty($translation->created_date) && $translation->created_date !== '0000-00-00 00:00:00') ? new \DateTime($translation->created_date) : null,
								referenceId: $translation->reference_id,
								referenceTable: $translation->reference_table,
								referenceField: $translation->reference_field,
							);

							if($this->languageRepository->flush($languageEntity))
							{
								$result[] = true;
								if (Factory::getApplication()->isClient('cli'))
								{
									$index++;
									echo "\r\033[33m$index orphans repaired for language $language \033[0m";
								}
							}
						}
						else
						{
							$result[] = true;
						}
					}
				}
			}
		}
		catch (\Exception $e)
		{
			throw new \RuntimeException('Failed to repair orphan language entries: ' . $e->getMessage(), 0, $e);
		}

		if (Factory::getApplication()->isClient('cli'))
		{
			if($index === 0)
			{
				echo "No orphan language entries found.\n";
			}
			echo "\n";
		}

		return !in_array(false, $result, true);
	}

	private function getLanguageFiles(array $languages): array
	{
		$files = [];

		foreach ($languages as $language)
		{
			$override_file = JPATH_BASE . '/language/overrides/' . $language . '.override.ini';
			if (file_exists($override_file))
			{
				$files[] = $override_file;
			}
		}

		return $files;
	}
}