<?php
/**
 * @package     Joomla
 * @subpackage  com_emundus
 *
 * @copyright   Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

// No direct access to this file
use Joomla\CMS\Language\Text;

defined('_JEXEC') or die('Restricted Access');

Text::script('BACK');
Text::script('COM_EMUNDUS_OPTIONAL');
Text::script('COM_EMUNDUS_MULTISELECT_NORESULTS');
Text::script('COM_EMUNDUS_GLOBAL_PARAMS_SECTION_MAIL_CHECK_INPUT_MAIL');

Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_NAME');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_LOCATION');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_IS_CONFERENCE_LINK');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_MANAGER');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_AVAILABLE_FOR');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_AVAILABLE_FOR_CAMPAIGNS');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_CAMPAIGNS_HELPTEXT');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_PROGRAMS_HELPTEXT');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_AVAILABLE_FOR_PROGRAMS');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_CAMPAIGNS');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_PROGRAMS');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_CREATE');
Text::script('COM_EMUNDUS_ONBOARD_EDIT_EVENT_GLOBAL_CREATE');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_ADD_LOCATION');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_LOCATION_SELECT');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_MANAGER_PLACEHOLDER');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_CONFERENCE_ENGINE');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_CONFERENCE_ENGINE_LINK');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_CONFERENCE_ENGINE_TEAMS');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_GENERATE_LINK_BY');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_GENERATE_LINK_BY_HELPTEXT');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_GENERATE_LINK_BY_RESERVATION');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_GENERATE_LINK_BY_SLOT');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_CONFERENCE_LINK');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_TEAMS_DISABLED');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_DURATION');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_DURATION_HELP');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_DURATION_MINUTES');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_DURATION_HOURS');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_BREAK_EVERY');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_BREAK_EVERY_HELP');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_BREAK_TIME');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_BREAK_TIME_HELP');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_CALENDAR');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_CALENDAR_HELP');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_BOOKED_SLOT_NUMBER');
Text::script('COM_EMUNDUS_ONBOARD_ADD_SLOT');
Text::script('COM_EMUNDUS_ONBOARD_EDIT_SLOT');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_USERS_PLACEHOLDER');
Text::script('COM_EMUNDUS_ONBOARD_ADD_SLOT_CREATE');
Text::script('COM_EMUNDUS_ONBOARD_ADD_SLOT_EDIT');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_ROOM');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_CAPACITY');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_CAPACITY_PLACEHOLDER');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_MORE_INFOS');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_MORE_INFOS_PLACEHOLDER');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_START_DATE');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_END_DATE');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_ROOM_SELECT');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_AVAILABLE_TO_SHOW');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_AVAILABLE_TO_SHOW_HELP');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_CAN_BOOK_UNTIL');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_CAN_BOOK_UNTIL_DAYS');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_CAN_BOOK_UNTIL_DATE');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_CAN_CANCEL');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_CAN_CANCEL_UNTIL');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_CAN_CANCEL_UNTIL_DAYS');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_CREATE');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_PLEASE_CREATE_FIRST');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_SAVED');
Text::script('COM_EMUNDUS_ONBOARD_ADD_SLOT_DELETE');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_DELETE_CONFIRM');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_DELETE_CONFIRM_TEXT');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_DELETE_CONFIRM_YES');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_DELETE_CONFIRM_NO');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_DELETED');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_SETUP_SUCCESS');
Text::script('COM_EMUNDUS_ONBOARD_ADD_SLOT_REPEAT');
Text::script('COM_EMUNDUS_ONBOARD_ADD_SLOT_REPEAT_NONE');
Text::script('COM_EMUNDUS_ONBOARD_ADD_SLOT_REPEAT_SELECTED');
Text::script('COM_EMUNDUS_ONBOARD_ADD_SLOT_EDIT_ONLY_ONE');
Text::script('COM_EMUNDUS_ONBOARD_ADD_SLOT_EDIT_ALL_FUTURES');
Text::script('COM_EMUNDUS_ONBOARD_ADD_SLOT_EDIT_ALL');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_BREAK_EVERY_END_TEXT');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_DATE_ERROR');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_DATE_ERROR_BEFORE_NOW');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_DURATION_ERROR');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SAVED');

Text::script('COM_EMUNDUS_ONBOARD_ADD_LOCATION');
Text::script('COM_EMUNDUS_ONBOARD_ADD_LOCATION_CREATE');
Text::script('COM_EMUNDUS_ONBOARD_ADD_LOCATION_NAME');
Text::script('COM_EMUNDUS_ONBOARD_ADD_LOCATION_ADDRESS');
Text::script('COM_EMUNDUS_ONBOARD_ADD_LOCATION_ROOMS');
Text::script('COM_EMUNDUS_ONBOARD_ADD_LOCATION_ROOM_NAME');
Text::script('COM_EMUNDUS_ONBOARD_PARAMS_ADD_REPEATABLE_ROOM');
Text::script('COM_EMUNDUS_ONBOARD_ADD_LOCATION_ROOM_SPECS');
Text::script('COM_EMUNDUS_ONBOARD_ADD_LOCATION_DESCRIPTION');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_CREATED');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SLOT_DURATION_REQUIRED');

Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SCHEDULE');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_CALENDAR');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_EMAILS');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_NOTIFICATIONS_APPLICANT_NOTIFY');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_NOTIFICATIONS_APPLICANT_NOTIFY_EMAIL');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_GLOBAL_EMAIL_SELECT');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_SAVE_AND_EXIT');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_NOTIFICATIONS_APPLICANT_RECALL');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_NOTIFICATIONS_APPLICANT_RECALL_EMAIL');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_NOTIFICATIONS_APPLICANT_RECALL_FREQUENCY');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_NOTIFICATIONS_APPLICANT_RECALL_FREQUENCY_END_TEXT');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_NOTIFICATIONS_MANAGER_RECALL');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_NOTIFICATIONS_MANAGER_RECALL_FREQUENCY_END_TEXT');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_NOTIFICATIONS_MANAGER_RECALL_EMAIL');
Text::script('COM_EMUNDUS_ONBOARD_ADD_EVENT_NOTIFICATIONS_USERS_RECALL');

Text::script('COM_EMUNDUS_WANT_EXIT_FORM_TITLE');
Text::script('COM_EMUNDUS_WANT_EXIT_FORM_TEXT');
Text::script('COM_EMUNDUS_WANT_EXIT_FORM_YES');
Text::script('COM_EMUNDUS_WANT_EXIT_FORM_NO');

Text::script('COM_EMUNDUS_EVENTS_ARE_YOU_SURE_CANCEL_RESERVATION');
Text::script('COM_EMUNDUS_EVENTS_CANCEL_RESERVATION');
Text::script('COM_EMUNDUS_EVENTS_INFO_BEFORE_CANCEL_RESERVATION');
Text::script('COM_EMUNDUS_EVENTS_CHANGE_MY_SLOT');
Text::script('COM_EMUNDUS_EVENTS_CANCEL');
Text::script('COM_EMUNDUS_EVENTS_RESERVATION_DELETED');
Text::script('COM_EMUNDUS_EVENTS_MY_RESERVATIONS');
Text::script('COM_EMUNDUS_EVENTS_NO_RESERVATION_FOUND');
Text::script('COM_EMUNDUS_EVENTS_REMOTE_LOCATION');
Text::script('COM_EMUNDUS_EVENTS_ONSITE_LOCATION');
Text::script('COM_EMUNDUS_EVENTS_JOIN_VIDEOCONFERENCE');
Text::script('COM_EMUNDUS_EVENT_CANT_BOOK_UNTIL_DATE');
Text::script('COM_EMUNDUS_EVENT_CANT_BOOK_NOW');
Text::script('COM_EMUNDUS_EVENT_CANT_BOOK_FROM_DATE');


$lang         = JFactory::getLanguage();
$short_lang   = substr($lang->getTag(), 0, 2);
$current_lang = $lang->getTag();
$languages    = JLanguageHelper::getLanguages();
if (count($languages) > 1) {
	$many_languages = '1';
}
else {
	$many_languages = '0';
}

$user               = JFactory::getUser();
$coordinator_access = EmundusHelperAccess::asCoordinatorAccessLevel($user->id);
$sysadmin_access    = EmundusHelperAccess::isAdministrator($user->id);

require_once(JPATH_BASE . DS . 'components' . DS . 'com_emundus' . DS . 'helpers' . DS . 'cache.php');
$hash = EmundusHelperCache::getCurrentGitHash();
?>

<div id="em-component-vue"
     component="Events/ViewBooking"
     coordinatorAccess="<?= $coordinator_access ?>"
     sysadminAccess="<?= $sysadmin_access ?>"
     shortLang="<?= $short_lang ?>" currentLanguage="<?= $current_lang ?>"
     manyLanguages="<?= $many_languages ?>">
</div>

<script type="module" src="media/com_emundus_vue/app_emundus.js?<?php echo $hash ?>"></script>
